Feat/unj1 s 1304 consulter le d tail d une formation
DNUM-SocialGouv/1j1s-front pull request #1008
Opened 2023-03-01 17:12 UTC by Naorid

2023-03-06 16:32 UTC, olivocto commented on src/server/formations/domain/formation.repository.ts
> +import { Formation, FormationFiltre,RésultatRechercheFormation } from './formation';
manque un espace par ici

2023-03-06 16:46 UTC, olivocto commented on src/client/components/features/Formation/Consulter/ConsulterFormation.tsx
> +import { Formation } from '~/server/formations/domain/formation';
je pense que ça va pas. Dans un composant d'affichage côté Client je ne m'attend pas à voir un fichier (ou type) importé depuis le serveur.
On devrait peut-être en discuter tous ensemble mais je pense qu'il faudrait dupliquer l'interface

2023-03-06 16:47 UTC, olivocto commented on src/client/components/features/Formation/Consulter/ConsulterFormation.tsx
> +				{(formation.adresse.adresseComplète || formation.contact.email || formation.contact.tel || formation.contact.url) &&
et si on faisait des variables intermédiaires?

2023-03-08 13:54 UTC, olivocto commented on src/server/formations/useCases/consulterFormation.useCase.ts
> +		return this.repository.get(id, filtre);
je ne comprend pas pourquoi tu passes le filtre ici

2023-03-08 13:55 UTC, olivocto commented on src/server/formations/infra/repositories/apiLaBonneAlternanceFormation.ts
> +	'duree-indicative': string
pourquoi tu mets les key entre quote?

2023-03-08 13:55 UTC, olivocto commented on src/server/formations/infra/repositories/apiLaBonneAlternanceFormation.ts
> +		'nombre-heures-centre': number
pourquoi tu mets les key entre quote?

2023-03-08 13:55 UTC, olivocto commented on src/server/formations/infra/repositories/apiLaBonneAlternanceFormation.ts
> +		'nombre-heures-entreprise': number
pourquoi tu mets les key entre quote?

2023-03-08 13:55 UTC, olivocto commented on src/server/formations/infra/repositories/apiLaBonneAlternanceFormation.ts
> +			'code-postal': string
pourquoi tu mets les key entre quote?

2023-03-08 13:57 UTC, olivocto commented on src/server/formations/infra/repositories/apiLaBonneAlternanceFormation.ts
> +export interface ApiLaBonneAlternanceFormationRechercheResponse {
pour toutes les interfaces qui suivent, tous les champs sont en mandatory. Est-on sur que l'on reçoit toujours tout?

2023-03-08 16:16 UTC, olivocto commented on src/server/formations/infra/repositories/apiLaBonneAlternanceFormation.mapper.ts
> +	const arr = [adresse, codePostal, ville].filter((elem) => elem !== '');
ne sois pas timide tu peux écrire les mots en entier

2023-03-08 16:16 UTC, olivocto commented on src/server/formations/infra/repositories/apiLaBonneAlternanceFormation.mapper.ts
> +	const arr = [adresse, codePostal, ville].filter((elem) => elem !== '');
et arr c'est interdit, un nom de variable explicite sera un plus

2023-03-09 09:31 UTC, olivocto commented on src/server/formations/infra/repositories/apiLaBonneAlternanceFormation.repository.ts
> +	async get(id: string, filtre?: FormationFiltre): Promise<Either<Formation>> {
il se passe beaucoup de choses par ici.
Il faudrait, pour + de lisibilité, passer par des fonctions intermédiaires avec des noms auto-portant surtout pour tout ce qui se passe dans le catch

2023-03-09 09:36 UTC, olivocto commented on src/server/formations/infra/repositories/apiLaBonneAlternanceFormation.mapper.ts
> +export const mapRésultatRechercheFormationToFormation = (résultatRechercheFormation: RésultatRechercheFormation):Formation => ({
le nom est-il assez explicite? Il pourrait transparaitre  la spécificité de se mapper lié au fait que la formation n'est pas retourné de façon habituelle, qu'est ce que tu en penses?

2023-03-09 09:36 UTC, olivocto commented on src/server/formations/domain/formation.repository.ts
> +import { Formation, FormationFiltre, RésultatRechercheFormation } from './formation';
relative path?

2023-03-09 09:38 UTC, olivocto commented on src/pages/formations/apprentissage/[id].page.tsx
> +function convertUndefinedToNull<T>(payload: T): T {
bon ça c'est super cool, je l'ai vu dans la pr de Gafi, est-ce qu'on ne le sortirait pas pour pouvoir l'utiliser partout?

2023-03-09 09:49 UTC, olivocto commented on src/client/components/features/Formation/Rechercher/RechercherFormation.tsx
> +			{résultatList.map((formation: RésultatRechercheFormation) => (
pourquoi le typer ? C'est pas sous-entendu ?

2023-03-09 09:54 UTC, olivocto commented on src/client/components/features/Formation/Consulter/ConsulterFormation.tsx
> +				{formation.nomEntreprise && <h2 className={commonStyles.sousTitre}>{formation.nomEntreprise}</h2>}
commonStyles.sousTitre ne semble pas exister

2023-03-09 09:58 UTC, olivocto commented on src/client/components/features/Formation/Consulter/ConsulterFormation.test.tsx
> +describe('ConsulterFormation', () => {
jolie raccourci pour les tests mais ça ne fonctionnera pas. Tu ne peux pas vraiment savoir ce que tu testes quand tu écris :
expect(screen.getByText(formation.titre || '')).toBeInTheDocument();
|| '' va être vrai pour n'importe quel élément.
Je t'invite à fortement copié le fichier de tests de GAFi pour l'aternance

2023-03-09 10:01 UTC, olivocto requested changes
quelques petites choses à revoir mais dans l'ensemble c'est top

2023-03-09 10:11 UTC, Naorid commented on src/client/components/features/Formation/Consulter/ConsulterFormation.tsx
> +import { Formation } from '~/server/formations/domain/formation';
Pour moi c'est un des + de next, pas se retrouver avec 20 types qui ont le meme contenu

2023-03-09 10:26 UTC, Naorid commented on src/server/formations/infra/repositories/apiLaBonneAlternanceFormation.mapper.ts
> +export const mapRésultatRechercheFormationToFormation = (résultatRechercheFormation: RésultatRechercheFormation):Formation => ({
t'as raison c'est pas super explicite
apres j'ai pas l'impression que le contexte devrait être ajouté coté mapper. J'ai ajouté une méthode dans le repo (getFormationFromRésultatsRecherche), t'en penses quoi ?

2023-03-09 10:29 UTC, Naorid commented on src/server/formations/domain/formation.repository.ts
> +import { Formation, FormationFiltre, RésultatRechercheFormation } from './formation';
Tu feras gaffe en français on mets un espace entre la fin du mot et le point d'interrogation 🙄.

2023-03-09 11:13 UTC, Naorid commented on src/client/components/features/Formation/Consulter/ConsulterFormation.test.tsx
> +describe('ConsulterFormation', () => {
J'ai fait une mise a jour je te laisse regarder.
(j'ai choisi de pas faire un test pour chaque élément parce que je trouve que ça fait trop de bruit)

2023-03-09 12:45 UTC, olivocto commented on src/pages/formations/apprentissage/[id].page.tsx
> +	usePopstate();
pourquoi tu utilises ce hook ici?

2023-03-09 14:39 UTC, olivocto approved these changes

2023-03-10 08:55 UTC, merged