feat(faq): ajout des questions sur la page faq depuis le cms
DNUM-SocialGouv/1j1s-front pull request #1037
Opened 2023-03-09 16:08 UTC by olivocto

UNJ1S-940

2023-03-13 15:05 UTC, Naorid approved these changes

2023-03-13 15:05 UTC, Naorid commented on src/pages/faq/index.page.tsx
> +	if (!isFeatureActive) return <ErrorUnavailableService/>;
Je soutiens cette démarche de ne pas créer un composant dans tous les cas. Il faut arreter avec les index.page qui font passe plat ✊

2023-03-13 15:05 UTC, Naorid commented on src/pages/faq/[id].page.tsx
> +	};
Meme com que sur le ```index.page.tsx```

2023-03-13 15:05 UTC, Naorid commented on src/pages/faq/[id].page.tsx
> +}
Je comprends pas trop l'interet d'un getStaticPath ici 🤔

2023-03-13 16:40 UTC, olivocto commented on src/pages/faq/[id].page.tsx
> +}
et bien ça va permettre de build toutes les pages en statiques au build et non au runtime, n'est-ce pas merveilleux?

2023-03-16 09:55 UTC, Mintoo200 requested changes
Par contre tu feras gaffe, tu commence à faire des PR à la Florian.

2023-03-16 09:55 UTC, Mintoo200 commented on src/client/components/ui/Radio/Radio.tsx
>  	}, [id]);
Tu peux remplacer tout ce block par un useID et un peut de logique à l'utilisation : 
```tsx
const generatedID = useID();
const actualID = id ?? generatedID
```
En réalité je pense que le meilleur nommage serait : 
```tsx
export function Radio({ id: propsID, label, className, ...rest } : RadioProps) {
  const generatedID = useID();
  const id = propsID ?? generatedID
  ...
}
```

2023-03-16 09:55 UTC, Mintoo200 commented on src/pages/espace-jeune/index.page.tsx
> +		<>
❤️

2023-03-16 09:55 UTC, Mintoo200 commented on src/pages/faq/[id].page.tsx
> +}
👍

2023-03-16 09:55 UTC, Mintoo200 commented on src/pages/faq/[id].page.tsx
> +}
Maintenant qu'elle est utilisée à plusieurs endroit (et qu'on sait qu'elle sera utiliser régulièrement), ça vaudrait le coup de l'extraire dans un fichier à part et donc de la tester unitairement

2023-03-16 09:55 UTC, Mintoo200 commented on src/pages/faq/[id].page.tsx
> +	};
Pour éviter de la redéfinir à chaque fois, tu peux l'extraire en global et prendre en params le `faqRéponse` en question

2023-03-16 09:55 UTC, Mintoo200 commented on src/pages/faq/index.page.module.scss
> +     }
Je l'aurais bien remonté dans les déclarations pour le h3

2023-03-16 09:55 UTC, Mintoo200 commented on src/pages/faq/index.page.test.tsx
> +			}
```suggestion
			const listeDeQuestion = screen.getByRole('list');
			const questions = within(listeDeQuestion).getAllByRole('listitem');
			
			questions.forEach((question, index) => {
				const lien = within(question).getByRole('link');
				expect(lien).toHaveTextContent(listeDeQuestionRéponse[index].problématique);
				expect(lien).toHaveAttribute('href', `/faq/${listeDeQuestionRéponse[index].slug}`);
			});
```

2023-03-16 09:55 UTC, Mintoo200 commented on src/pages/faq/index.page.tsx
> +						{listeDeQuestionRéponse?.map((question) => <li key={uuidv4()}>
`uuidv4` va te renvoyer un nouvel ID à chaque appel donc tu re-render dans tous les cas. Si `question.problématique` n'est pas forcément unique, dans le type `Question` tu as un `slug` qui en théorie devra toujours être unique au sein de la liste donc tu peux utiliser ça comme key.
**Dans le pire des cas**, tu peux toujours utiliser l'index (que tu récupère en 2e argument du map).

2023-03-16 09:55 UTC, Mintoo200 commented on src/server/cms/infra/repositories/strapi.repository.test.ts
> +		describe('quand la liste des questions n’est trouvée', () => {
```suggestion
		describe('quand la liste des questions n’est pas trouvée', () => {
```

2023-03-16 09:55 UTC, Mintoo200 commented on src/server/cms/infra/repositories/strapi.repository.test.ts
> +		describe('quand la question réponse n’est trouvée', () => {
```suggestion
		describe('quand la question réponse n’est pas trouvée', () => {
```

2023-03-16 11:03 UTC, Mintoo200 approved these changes

2023-03-16 12:20 UTC, merged