feat: ajout appel adresse api pour commune
DNUM-SocialGouv/1j1s-front pull request #104
Opened 2022-07-01 12:31 UTC by olivocto

2022-07-04 07:49 UTC, OCTO-CLEM requested changes

2022-07-04 07:49 UTC, OCTO-CLEM commented on src/server/localisations/domain/localisationAvecCoordonnées.ts
> +    lon: number
longitude
latitude

Ca mange pas de pain :D

2022-07-04 07:49 UTC, OCTO-CLEM commented on src/server/localisations/infra/repositories/apiAdresse.repository.ts
> +      const communeList = response.data.features.map((adresse) => ({
```
const résultats = response.data.features.map(({ properties, geometry }) => ({
        code: properties.citycode,
        coordonnées: {
          lat: geometry.coordinates[1],
          lon: geometry.coordinates[0],
        },
        libelle: properties.label,
        ville: properties.city,
      }));
      return createSuccess({ résultats });
```

ca fait gagner un peu de place mais comme tu veux :)

2022-07-04 07:49 UTC, OCTO-CLEM commented on src/server/localisations/domain/localisationAvecCoordonnées.ts
> +  coordonnées: Commune.Coordonnées
j'aurais pas créé d'interface pour 2 attributs perso ça fait gagner un peu de code et j'trouve latitude, longitude on comprend que ce que c'est direct

2022-07-04 07:49 UTC, OCTO-CLEM commented on src/pages/api/communes/index.tsx
> +import type { NextApiRequest, NextApiResponse } from 'next';
il te manque ton petit test d'api :)

2022-07-04 09:10 UTC, paulgallocto approved these changes

2022-07-05 07:39 UTC, OCTO-CLEM approved these changes

2022-07-05 08:14 UTC, merged