feat(alternance): détail peJobs
DNUM-SocialGouv/1j1s-front pull request #1042
Opened 2023-03-10 10:29 UTC by Naorid

2023-03-14 12:48 UTC, juliebrunetto83 commented on src/client/components/features/Alternance/Detail/Detail.tsx
> +					<Link appearance={'asPrimaryButton'} type={'external'} href={annonce.url} className={styles.postuler}>Postuler sur Pole Emploi</Link>
C'est Pôle Emploi je crois

2023-03-14 16:00 UTC, Mintoo200 requested changes

2023-03-14 16:00 UTC, Mintoo200 commented on src/server/alternances/infra/repositories/apiLaBonneAlternance.repository.ts
> +	}
🤔

2023-03-14 16:00 UTC, Mintoo200 commented on src/client/components/features/Alternance/Detail/Detail.tsx
> +								<span>{annonce.durée}</span>
Tu peux laisser `<time>`

2023-03-14 16:00 UTC, Mintoo200 commented on src/server/alternances/infra/repositories/apiLaBonneAlternance.mapper.ts
> +		durée: alternance.job.dureeContrat ? `${alternance.job.dureeContrat} an${alternance.job.dureeContrat > 1 ? 's' : ''}` : undefined,
J'aurais bien extrait ça dans une fonction pour éviter d'avoir un pâté de code au milieu d'une autre fonction

2023-03-14 16:00 UTC, Mintoo200 commented on src/server/alternances/infra/repositories/apiLaBonneAlternance.repository.ts
> +	}
Plus explicite qu'un commentaire, une constante (voire variable d'env) pourrait donner la même info et éviter les magic numbers (e.g. `PoleEmploiIDLength` ou un truc dans le genre)

2023-03-14 16:02 UTC, Naorid commented on src/server/alternances/infra/repositories/apiLaBonneAlternance.repository.ts
> +	}
🤠

2023-03-14 16:17 UTC, Naorid commented on src/client/components/features/Alternance/Detail/Detail.tsx
> +export function Detail({ annonce }: { annonce: Alternance }) {
A discuter en direct 🫠

2023-03-14 16:19 UTC, Naorid commented on src/server/alternances/infra/repositories/apiLaBonneAlternance.repository.ts
> +	}
javou

2023-03-15 14:02 UTC, Mintoo200 approved these changes

2023-03-15 14:02 UTC, Mintoo200 commented on src/server/alternances/infra/repositories/apiLaBonneAlternance.mapper.ts
> +		durée: alternance.job.dureeContrat ? parseDurée(alternance.job.dureeContrat) : undefined,
Je pense que tu peux mettre la gestion du `undefined` direct dans la fonction comme ça ici t'as que l'appel à la fonction

2023-03-15 14:02 UTC, Mintoo200 commented on src/server/alternances/infra/repositories/apiLaBonneAlternance.repository.ts
> +const PoleEmploiIdLength = 7;
Les constantes devraient être en ALL_CAPS avec des "_"

2023-03-15 14:09 UTC, Naorid commented on src/server/alternances/infra/repositories/apiLaBonneAlternance.repository.ts
> +const PoleEmploiIdLength = 7;
oups bien vu 👍

2023-03-15 14:23 UTC, merged