feat(alternance): Postuler offre Matcha
DNUM-SocialGouv/1j1s-front pull request #1046
Opened 2023-03-13 17:06 UTC by Naorid

2023-03-14 13:52 UTC, Drastal commented on src/client/components/features/Alternance/Detail/Detail.module.scss
> +  min-height: 1300px;
Traduire en rem pour que ça s'adapte à la taille de police.

2023-03-14 17:00 UTC, Naorid commented on src/client/components/features/Alternance/Detail/Detail.module.scss
> +  }
oke

2023-03-15 18:04 UTC, Drastal requested changes

2023-03-15 18:04 UTC, Drastal commented on src/client/components/features/Alternance/Detail/DetailAlternance.type.ts
>  export type DetailAlternance = {
C'est quoi la diff avec une `Alternance` ?

2023-03-15 18:04 UTC, Drastal commented on src/pages/apprentissage/[id].page.tsx
>  	};
En gros tout cet objet c'est 
```
{
  ...annonce.result,
  dateDébut: annonce.result.dateDébut?.toISOString(),
}
```

2023-03-16 16:24 UTC, juliebrunetto83 commented on src/client/components/features/Alternance/Detail/Detail.tsx
> +	const iframePostulerMatcha = `${process.env.NEXT_PUBLIC_LA_BONNE_ALTERNANCE_URL}postuler?caller=${caller}&itemId=${annonce.id}&type=matcha`;
J'ai ajouté en sortie du repository une url dans les offres matchas qui est l'url de l'iframe. Est ce que ça te parait ok ?

2023-03-17 16:41 UTC, Drastal approved these changes

2023-03-17 16:41 UTC, Drastal commented on src/server/alternances/infra/repositories/apiLaBonneAlternance.mapper.ts
> +		url: alternance.job.id ? `${process.env.NEXT_PUBLIC_LA_BONNE_ALTERNANCE_URL}postuler?caller=1jeune1solution&itemId=${alternance.job.id}&type=matcha` : undefined,
Je trouve que url n'est pas très explicite 🤔  Je préciserai les notions de `postuler` et `lien`. `lienPostuler` tout simplement ?

2023-03-17 16:41 UTC, Drastal commented on src/client/components/features/Alternance/Detail/Detail.tsx
> +}
Yes ! Je pense que ce genre de fonction trouve sa place dans le domain :)
Et est-ce que le typage du paramètre d'entrée peut être plus simplement `source: Alternance.Source` ?

2023-03-21 09:06 UTC, merged