feat(alternance): recuperation de video depuis Strapi
DNUM-SocialGouv/1j1s-front pull request #1184
Opened 2023-04-19 07:36 UTC by Naorid

2023-04-28 08:32 UTC, juliebrunetto83 reviewed
![image](https://user-images.githubusercontent.com/122871677/235097242-eeaedbae-6e43-4bbb-b08b-e1f6d52bb1ad.png)
Il y a un problème avec le css en mobile, j'ai mon texte qui ne se coupe pas

Pourquoi avoir mis un  '    white-space: pre;' ?

2023-04-28 08:36 UTC, juliebrunetto83 commented on src/client/components/features/CampagneApprentissage/CampagneApprentissageJeunes/CampagneApprentissageJeunes.test.tsx
> +		it('si j’ai selectionné une vidéo, le focus se retrouve avant la vidéo', async () => {
Pour moi à chaque fois qu'il y a un 'si' c'est qu'il manque un describe

2023-04-28 08:36 UTC, juliebrunetto83 commented on src/client/components/features/CampagneApprentissage/CampagneApprentissageJeunes/CampagneApprentissageJeunes.tsx
> +
ligne videeee

2023-04-28 08:37 UTC, juliebrunetto83 commented on src/client/components/features/CampagneApprentissage/VideosCampagneApprentissage/VideosCampagneApprentissage.module.scss
> +    //grid-template-columns: repeat(auto-fit, minmax(50rem, 1fr));
tu l'as oublié ça

2023-04-28 08:38 UTC, juliebrunetto83 commented on src/client/components/features/CampagneApprentissage/VideosCampagneApprentissage/VideosCampagneApprentissage.module.scss
> +@import "@styles/utilities";
utiliser @use "@styles/utilities";

2023-04-28 08:38 UTC, juliebrunetto83 commented on src/client/components/features/CampagneApprentissage/VideosCampagneApprentissage/VideosCampagneApprentissage.module.scss
> +$padding-horizontal: 2rem;
Je ne comprends pas l'interet de créer une variable pour l'utiliser qu'une fois ?

2023-04-28 08:40 UTC, juliebrunetto83 commented on src/client/components/features/CampagneApprentissage/VideosCampagneApprentissage/VideosCampagneApprentissage.module.scss
> +%container {
pareil ici, autant mettre directement dans le .videos l'ensemble des propriétés

2023-04-28 08:41 UTC, juliebrunetto83 commented on src/client/components/features/CampagneApprentissage/VideosCampagneApprentissage/VideosCampagneApprentissage.module.scss
> +@include media(large) {
Dans nos conventions on a décidé de mettre les 'médias large' au fur et à mesure pour simplifier la lecture du code

2023-04-28 08:42 UTC, juliebrunetto83 commented on src/client/components/features/CampagneApprentissage/VideosCampagneApprentissage/VideosCampagneApprentissage.module.scss
> +  &Container {
On n'utilise plus le &Container mais  & .videoContainer

2023-04-28 08:43 UTC, juliebrunetto83 commented on src/client/components/features/CampagneApprentissage/VideosCampagneApprentissage/VideosCampagneApprentissage.module.scss
> +  &Content {
idem ici & .transcriptionContent

2023-04-28 08:43 UTC, juliebrunetto83 commented on src/client/components/features/CampagneApprentissage/VideosCampagneApprentissage/VideosCampagneApprentissage.module.scss
> +  &Content {
je te laisse regarder il y en a d'autres

2023-04-28 08:44 UTC, juliebrunetto83 commented on src/client/components/features/CampagneApprentissage/VideosCampagneApprentissage/VideosCampagneApprentissage.module.scss
> +  .temoignage {
pourquoi 'temoignages' au lieu de 'temoignage'? on peut uniformiser

2023-04-28 08:50 UTC, juliebrunetto83 commented on src/client/components/features/CampagneApprentissage/CampagneApprentissageJeunes/CampagneApprentissageJeunes.test.tsx
> +
Il manque un test si pas de video, alors on affiche rien

2023-04-28 08:56 UTC, juliebrunetto83 commented on src/pages/apprentissage-jeunes/index.page.test.tsx
> +					expect(result).toMatchObject({ props: {} });
Les props ne devraient pas être vide ici c'est étrange ...?

2023-04-28 08:58 UTC, juliebrunetto83 commented on src/pages/apprentissage-jeunes/index.page.tsx
> +				{/*<ul>*/}
???

2023-04-28 08:59 UTC, juliebrunetto83 commented on src/server/cms/configuration/dependencies.container.ts
> +		récupérerVidéosCampagneApprentissage: new RécupérerVidéosCampagneApprentissageUseCase(cmsRepository),
Est ce que tu peux enlever les accents stp ?

2023-04-28 09:06 UTC, juliebrunetto83 commented on src/server/cms/infra/repositories/strapi.repository.ts
> +	mapStrapiListeActualités, mapVideoCampagneApprentissage,
'mapVideoCampagneApprentissage' à la ligne

2023-04-28 09:09 UTC, juliebrunetto83 commented on src/server/cms/useCases/récupérerVidéosCampagneApprentissage.useCase.ts
> +export class RécupérerVidéosCampagneApprentissageUseCase {
accent

2023-04-28 09:48 UTC, juliebrunetto83 requested changes
Le todo a été fait ?

2023-05-02 09:12 UTC, Naorid commented on src/pages/apprentissage-jeunes/index.page.tsx
> +				{/*<ul>*/}
oupsi 😇

2023-05-02 09:36 UTC, Naorid commented on src/pages/apprentissage-jeunes/index.page.test.tsx
> +				it('renvoie des props vides', async () => {
C'est parce qu'il manquait le createSuccess autour du {} 🤕

2023-05-02 10:38 UTC, suli-octo commented on src/client/components/features/CampagneApprentissage/CampagneApprentissageJeunes/CampagneApprentissageJeunes.tsx
> +			}
c'est vraiment voulu par Joy ce changement d'ordre quand on passe en mobile ? enfin que ça a un sens ? puisque sur la maquette d'entreprise il n'y pas cette particularité

2023-05-02 10:38 UTC, suli-octo commented on src/client/components/features/CampagneApprentissage/VideosCampagneApprentissage/VideosCampagneApprentissage.tsx
> +		return null;
Tu veux dire quand on récupère nos vidéos de Strapi on est pas sur qu'il y ait toujours une liste ou pas ?

2023-05-02 12:05 UTC, juliebrunetto83 commented on src/client/components/ui/Button/button-component.module.scss
> -  white-space: nowrap;
Il n'y a pas une raison pour laquelle ça avait été fait comme ça ?

2023-05-02 12:07 UTC, juliebrunetto83 approved these changes

2023-05-02 15:46 UTC, merged