feat(alternance): ajout de la section découverte apprentissage
DNUM-SocialGouv/1j1s-front pull request #1238
Opened 2023-05-02 13:34 UTC by juliebrunetto83

2023-05-02 16:16 UTC, Mintoo200 requested changes

2023-05-02 16:16 UTC, Mintoo200 commented on src/client/components/features/ServiceCard/Card/ServiceCard.module.scss
> +    }
J'ai l'impression que ces sélecteurs s'appliquent aux même éléments que plus haut (`.cardLogoContain` et `.cardLogo` semblent s'appliquer tous les deux au même élément que `.cardLogoCover` et `img` au même élément que `.cardLogoCover > img`). On peut peut-être les merger ? Ça permettrait probablement de se débarrasser de certaines propriétés

2023-05-02 16:16 UTC, Mintoo200 commented on src/client/components/features/ServiceCard/Card/ServiceCard.module.scss
> +      & .cardHeadline:after {
~~Techniquement ça fonctionne puisqu'[à une époque c'était la notation officielle](https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-elements#sect2) donc, pour être rétro-compatible, les navigateurs acceptent cette notation mais normalement les pseudo-éléments (`::before`, `::after`, `::backdrop`, ...) prennent `::` (contrairement aux pseudo-selecteur comme `:hover`, ...).~~
\
Ça n'a pas l'air d'être utilisé

2023-05-02 16:16 UTC, Mintoo200 commented on src/client/components/features/ServiceCard/Card/ServiceCard.tsx
> +	const imageClassName = classNames(styles.cardLogo, imageFit === 'contain' ? styles.cardLogoContain : styles.cardLogoCover);
Je ne sais pas trop quoi faire de ça 😕. Idéalement je passerai la card en composition pour éviter d'avoir des props pour chaque style qu'on veut pouvoir override et pour le title et le titleAs et le link et le linkLabel, ... mais ça demanderait un certain travail qui ne rentre pas forcément dans ce ticket

2023-05-03 05:49 UTC, juliebrunetto83 commented on src/client/components/features/CampagneApprentissage/CampagneApprentissageJeunes/PreparationApprentissage/PreparationApprentissage.tsx
> -					<h2 className={styles.titlePrepaApprentissage} id={'titre-section-preparation-apprentissage'}>
Oui c'est ce que je me disais, mais je ne savais pas comment faire comme il y a deux titres ... ?

2023-05-03 05:51 UTC, juliebrunetto83 commented on src/client/components/features/ServiceCard/Card/ServiceCard.module.scss
> +.serviceListWrapper {
Je n'ai pas changé le style du composant, il était comme ça à la base j'ai juste modifié la manière dont le style avait était écrit selon nos nouvelles règles (&Wrapper vs & .serviceListWrapper) 

Mais je peux le prendre dans mon ticket :)

2023-05-03 05:55 UTC, juliebrunetto83 commented on src/client/components/features/ServiceCard/Card/ServiceCard.module.scss
> +      & .cardHeadline:after {
Si ça l'est ... dans un des partners (SimulationAlternancePartner)

2023-05-03 05:57 UTC, juliebrunetto83 commented on src/client/components/features/ServiceCard/Card/ServiceCard.module.scss
> +      }
On en rediscute de vive voix, je n'ai pas trouvé de meilleure façon de faire

2023-05-03 06:13 UTC, juliebrunetto83 commented on src/client/components/features/ServiceCard/Card/ServiceCard.module.scss
> +    }
en fait, les classes cardLogo, cardLogoContain et cardLogoCover s'appliquent au même élément en fonction de ce qui est attendu, soit l'image prend toute la place soit c'est un logo et donc on applique cardLogoContain

Je suis pas sur de comprendre ta proposition

2023-05-03 13:31 UTC, Mintoo200 approved these changes

2023-05-04 15:23 UTC, merged