feat: activation panel cookies par défaut et ajout Adform pour la campagne
DNUM-SocialGouv/1j1s-front pull request #1241
Opened 2023-05-02 15:23 UTC by gmoocto

2023-05-10 07:34 UTC, gmoocto commented on src/client/services/analytics/analytics.service.test.ts
> +			serviceDefaultState: 'wait',
meta: permet d'afficher la fenêtre de cookie pour demander le consentement au chargement de la page

2023-05-10 07:36 UTC, gmoocto commented on src/pages/_document.page.tsx
> -				}
A remettre après les tests sur review app

2023-05-11 07:26 UTC, gmoocto commented on src/client/services/analytics/analytics.service.ts
> +	private initialiserAnalyticsCampagneDeCommunication(): void {
TODO : vérifier avec Lina / Laurent si on désactivera totalement adform après la campagne

2023-05-15 09:30 UTC, Naorid commented on src/client/services/analytics/analytics.service.test.ts
> +				window.location.pathname = '/apprentissage-jeunes';
La page été déplacé -> /choisir-apprentissage

2023-05-15 09:30 UTC, Naorid commented on src/client/services/analytics/analytics.service.test.ts
> +		describe('quand on est sur la page de campagne jeune', () => {
Est ce que ca doit etre uniquement sur la page campagne jeune ou aussi la partie employeur ?

2023-05-15 09:32 UTC, Naorid requested changes
Changer l'url ou s'appliquent les analytics

2023-05-15 15:12 UTC, Naorid approved these changes

2023-05-15 15:13 UTC, merged