Feat/128 filtrer résultat dès 16 ans
DNUM-SocialGouv/1j1s-front pull request #125
Opened 2022-07-15 14:37 UTC by AliElAmrani

2022-07-15 14:39 UTC, AliElAmrani commented on src/client/components/features/Engagement/FormulaireRecherche/FormulaireRechercheMissionEngagement.module.css
> +  flex-basis: 100%;
Je suis pas super fan de cette méthode pour mettre à la ligne la checkbox en display flex, je pense qu'il y a peut-être moyen de faire mieux pour mettre à la ligne une div en flex ?

2022-07-15 14:40 UTC, AliElAmrani commented on src/client/components/features/Engagement/Rechercher/RechercherMission.tsx
>  }
@paulgallocto avait proposé de passer par une énum pour éviter les incohérences sur la typo de services-civique ou service-civique, j'étais plutôt d'accord du coup je l'ai ajouté ici :)

2022-07-18 07:11 UTC, olivocto commented on src/client/hooks/useQueryParams.ts
> +  OUVERT_AUX_MINEURS = 'ouvertsAuxMineurs'
es-tu vraiment sur que ce soit utilisé? Ce fichier est supprimé dans la PR de Florian....

2022-07-18 07:13 UTC, olivocto commented on src/client/utils/engagementsCategory.utils.ts
>  export enum TypeEngagement {
pas sur que ce soit le bon fichier en tout cas pas le bon nommage. Que dirais-tu de engagementsCategory.enum.ts

2022-07-18 07:30 UTC, AliElAmrani commented on src/client/hooks/useQueryParams.ts
> +  OUVERT_AUX_MINEURS = 'ouvertsAuxMineurs'
Nope il ne l'est pas, j'ai dû le dupliquer par erreur quand je voulais rajouter le tag "Dès 16 ans"

2022-07-18 07:32 UTC, olivocto commented on tests/client/components/features/Engagement/FormulaireRecherche/FormulaireRechercheMissionEngagement.test.tsx
> +  describe('quand on filtre ouverts aux mineurs', () => {
quand on filtre avec ouverts aux mineurs

2022-07-18 08:02 UTC, olivocto commented on src/client/components/features/Engagement/FormulaireRecherche/FormulaireRechercheMissionEngagement.tsx
> +        <div className={styles.minorCheckboxWrapper}>
<img width="386" alt="image" src="https://user-images.githubusercontent.com/102825843/179468782-f79daff0-b8bd-4934-8e6c-27590f79bbeb.png">

2022-07-18 08:02 UTC, olivocto commented on src/client/components/features/Engagement/FormulaireRecherche/FormulaireRechercheMissionEngagement.tsx
> +        <div className={styles.minorCheckboxWrapper}>
la checkbox ne devrait-elle pas être avant le bouton rechercher?

2022-07-18 08:11 UTC, olivocto commented on src/client/components/features/Engagement/FormulaireRecherche/FormulaireRechercheMissionEngagement.tsx
> +  const [ouvertAuxMineurs, setOuvertAuxMineurs] = useState<boolean | string>('');
tu peux rester sur du boolean en filtrant côté getFormAsQuery

2022-07-18 08:12 UTC, olivocto requested changes
attention au respect de la maquette

2022-07-18 09:02 UTC, olivocto commented on src/client/components/features/Engagement/FormulaireRecherche/FormulaireRechercheMissionEngagement.module.scss
> +@include media(medium){
un ESPACE

2022-07-18 11:25 UTC, AliElAmrani commented on src/client/components/features/Engagement/FormulaireRecherche/FormulaireRechercheMissionEngagement.tsx
> +        <div className={styles.minorCheckboxWrapper}>
Pas sur la maquette 😌

2022-07-18 11:49 UTC, merged