feat(ui): adaptation du composant bouton
DNUM-SocialGouv/1j1s-front pull request #1264
Opened 2023-05-09 09:00 UTC by juliebrunetto83

2023-05-17 13:46 UTC, Mintoo200 requested changes

2023-05-17 13:46 UTC, Mintoo200 commented on src/client/components/ui/Hero/Hero.module.scss
> +        color: utilities.$brazil-red;
```suggestion
        color: utilities.$campagne-CEJ-primary;
```

2023-05-17 13:46 UTC, Mintoo200 commented on src/client/components/ui/Link/Link.module.scss
> +    margin-top: 0.5rem;
Vu que c'est en inline-flex, il y a pas moyen de le faire avec un `gap: .5rem;` ?

2023-05-17 13:46 UTC, Mintoo200 commented on src/client/components/ui/LinkStyledAsButton/LinkStyledAsButton.test.tsx
> +		it('retourne le composant Link avec un *tag a* directement et les propriétés target et rel', () => {
nitpick: Il vaut mieux ne pas parler de balise HTML dans le nom du test mais plutôt de rôle (puisque c'est ce qui est testé dans la fonction)

2023-05-17 13:46 UTC, Mintoo200 commented on src/client/components/ui/LinkStyledAsButton/LinkStyledAsButton.test.tsx
> +			expect(linkComponent.getAttribute('href')).toEqual('https://mon-lien-externe');
```suggestion
			expect(linkComponent).toHaveAttribute('href', 'https://mon-lien-externe');
```

2023-05-17 13:46 UTC, Mintoo200 commented on src/pages/europe/index.page.tsx
> +import { LinkStyledAsButton } from '../../client/components/ui/LinkStyledAsButton/LinkStyledAsButton';
import relatif

2023-05-17 13:46 UTC, Mintoo200 commented on src/styles/_utilities.scss
> +@import "media/mixins";
salut

2023-05-17 14:07 UTC, juliebrunetto83 commented on src/client/components/features/Evenement/RésultatRechercherEvenement.tsx
> +						className={styles.fakeLink}
je vois pas comment tu veux faire ça car le hover de la carte fait que le fakeLink est surligné

2023-05-17 14:26 UTC, juliebrunetto83 commented on src/client/components/ui/Link/Link.module.scss
> +    margin-top: 0.5rem;
je viens de voir que ce style ne sert plus :)

2023-05-19 08:45 UTC, Mintoo200 commented on src/client/components/features/Evenement/RésultatRechercherEvenement.tsx
> +						className={styles.fakeLink}
tu peux quand même mettre ça dans le CSS de la card 😮 
```scss
.cardComponent {
  // [...]
  &:hover .cardButtonQuaternary {
    color: red;
  }
}
```

2023-05-23 14:45 UTC, Mintoo200 approved these changes

2023-05-24 08:08 UTC, merged