[320] Ajout du bloc "Qu'est-ce que j'y gagne à long terme" du CEJ
DNUM-SocialGouv/1j1s-front pull request #137
Opened 2022-07-20 13:43 UTC by toma-benguigui

2022-07-21 13:31 UTC, Floby commented
Vu que la politique de contribution de ce dépôt c'est le squash+merge, je te propose de mettre un titre un peu sérieux à la pull request, vu que ce sera ça qui détermine le nom du commit qui restera dans l'histoire à la fin.

2022-07-22 13:41 UTC, olivocto commented on src/pages/contrat-engagement-jeune/QuEstCeQueJyGagne.tsx
> +      <li>Définir et bâtir un <strong>projet professionnel durable</strong></li>
la balise <strong> est utilisé à mauvais escient,
cette dernière n'a pas pour but de mettre une parcelle de texte en gras mais d'indiquer au navigateur (et lecteurs vocaux) l'importante du contenu de cette balise.
Aussi il faudrait la supprimer des composants si celle-ci n'apporte pas un caractère informatif particulier

2022-07-22 13:41 UTC, olivocto commented on src/pages/contrat-engagement-jeune/QuEstCeQueJyGagne.tsx
> +        {displayAccordion && <span className={styles.accordion}><AccordionComponent>{contenu}</AccordionComponent></span>}
attention, un peu de changement sur le merge de Sergen, ce sera à répercuter sur cette pr (le composant n'est plus wrappé dans un span par exemple)

2022-07-22 13:53 UTC, olivocto requested changes
je t'invite à voir avec Sergen pour un changement de place de fichier impactant,
il pourra te montrer les retours à faire

2022-07-26 12:10 UTC, merged