feat(entreprises): ajout d'un error management service
DNUM-SocialGouv/1j1s-front pull request #1378
Opened 2023-05-31 16:16 UTC by juliebrunetto83

2023-06-01 15:43 UTC, Mintoo200 requested changes

2023-06-01 15:43 UTC, Mintoo200 commented on src/server/cms/infra/repositories/strapi.repository.test.ts
> +				expect(result).toEqual(createSuccess(undefined));
```suggestion
				expect(result.instance).toEqual('success');
```

2023-06-01 15:43 UTC, Mintoo200 commented on src/server/emplois/infra/repositories/apiPoleEmploiOffre.repository.ts
> -
👍

2023-06-01 15:43 UTC, Mintoo200 commented on src/server/entreprises/infra/apiRejoindreLaMobilisationError.ts
> +		{ stacktrace: (<Error>e).stack },
On a pas moyen de checker le type plutôt que de caster ?
Si on cast ça veut dire qu'à cet endroit on **sait** que `e instanceof Error`, ça veut dire qu'il y a probablement un type guard manquant ou un typage invalid au dessus.
Si c'est pas le cas, c'est super dangereux de caster sans être certain, je préfèrerais un truc du style `{ stacktrace: e instanceof Error ? e.stack : null }` ou un truc dans le genre

2023-06-01 15:43 UTC, Mintoo200 commented on src/server/entreprises/infra/apiRejoindreLaMobilisationErrorManagement.service.ts
> +
```suggestion
```

2023-06-02 08:45 UTC, juliebrunetto83 commented on src/server/entreprises/infra/apiRejoindreLaMobilisationError.ts
> +		{ stacktrace: (<Error>e).stack },
ça m'a fait penser que j'avais oublier de supprimer ce fichier, on en a plus besoin maintenant :)

2023-06-02 11:13 UTC, Mintoo200 approved these changes

2023-06-02 14:16 UTC, merged