feat(formation) : ajout error management
DNUM-SocialGouv/1j1s-front pull request #1404
Opened 2023-06-05 15:02 UTC by suli-octo

2023-06-07 08:44 UTC, suli-octo commented on src/server/formations/infra/repositories/apiLaBonneAlternanceFormation.repository.ts
> +		// quand ils n'arrivent pas à faire leur tambouille interne, ils nous retournent une 500
laisser un commentaire ou renommer la fonction

2023-06-07 08:44 UTC, suli-octo commented on src/server/formations/infra/repositories/apiLaBonneAlternanceFormation.repository.ts
> +			return undefined; // ici le log et le retour sont décorrelés
ici le log et le retour sont décorrelés 
Cf le commentaire // SULI pas oui

2023-06-07 10:02 UTC, Mintoo200 requested changes

2023-06-07 10:02 UTC, Mintoo200 commented on src/server/formations/infra/repositories/apiLbaFormationErrorManagementServiceGet.ts
> +		super.handleFailureError(error, logInformation); // SULI pas ouf
Tu feras gaffe, c'est pas ouf

2023-06-07 13:24 UTC, suli-octo commented on src/server/formations/infra/repositories/apiLaBonneAlternanceFormation.repository.ts
> +			});
Utilisation du default car en soit c'est une erreur "interne", donc suppression du apiLbaFormationErrorManagementServiceGet

2023-06-08 10:15 UTC, suli-octo commented on src/server/formations/infra/repositories/apiLaBonneAlternanceFormation.repository.ts
> +		// quand ils n'arrivent pas à faire leur tambouille interne, ils nous retournent une 500
renommée

2023-06-08 14:22 UTC, Mintoo200 commented on src/server/formations/infra/repositories/apiLaBonneAlternanceFormation.repository.test.ts
> +								expect(httpClientService.post).toHaveBeenCalledTimes(0);
Bah en vrai, si tu te sens de le faire sur cette PR, idéalement tu peux expliciter cette règle dans 3 tests à part puisque c'est 4 fonctionnalités distinctes en mode
```ts
it('devrait récupérer la formation avec l'ID', () => {
  // ...
  expect(httpClientService.get).toHaveBeenCalledTimes(1);
  expect(httpClientService.get).toHaveBeenCalledWith('/get/id');
})
it('devrait récupérer la formation parmi la liste de recherche quand pas dispo avec l'ID', () => {
  // ...
  expect(httpClientService.get).toHaveBeenCalledTimes(2);
  expect(httpClientService.get).toHaveBeenCalledLastWith('/search');
})
it('devrait obtenir un lien de rdv', () => {
  // ...
  const formation = uneFormation({ cleMinistereEducatif: '/blah' });
  
  expect(httpClientService.post).toHaveBeenCalledTimes(1);
  expect(httpClientService.get).toHaveBeenCalledLastWith('/blah');
})

it('devrait ne pas requêter l'API pour le lien de rdv si pas de ministère', () => {
  // ...
  const formation = uneFormation({ cleMinistereEducatif: null });
  
  expect(httpClientService.post).toHaveBeenCalledTimes(0);
})

```

2023-06-09 12:49 UTC, suli-octo commented on src/server/formations/infra/repositories/apiLaBonneAlternanceFormation.repository.test.ts
> +										message: '[API LaBonneAlternance] impossible de créer le lien de demande de rdv pour une formation',
Ce qui me dérange c'est le cas par exemple d'un message 'impossible de récupérer une ressource', qu'on va faire passer en message en argument au handleFailureError, et y a plusieurs cas de repository où le message est identique. C'est moins intuitive car tu passes encore sur plusieurs fichiers avant de trouver l'endroit qui pose problème. Même si c'est 3/4 cliques ça reste moins direct.

On peut faire en sorte d'avoir la seule source de vérité, dans le répository avec un const API_LA_BONNE_ALTERNANCE = 'API LaBonneAlternance' et le réutiliser dans apiSource et dans le message en templating quand on appelle le handleFailureError, cette solution réconcilie les deux besoins

2023-06-12 08:15 UTC, Mintoo200 approved these changes

2023-06-12 08:38 UTC, suli-octo commented on src/server/formations/infra/repositories/apiLaBonneAlternanceFormation.repository.test.ts
> +										message: '[API LaBonneAlternance] impossible de créer le lien de demande de rdv pour une formation',
Mis d'accord sur le fait d'avoir des messages d'erreur unique, et l'error management préfixe le message à afficher avec  [apiSource]. A développer sur une autre PR

2023-06-12 08:38 UTC, merged