feat(formation-init): recuperer les formations initiales depuis l api onisep
DNUM-SocialGouv/1j1s-front pull request #1524
Opened 2023-06-23 13:18 UTC by suli-octo

2023-06-27 14:21 UTC, gmoocto requested changes

2023-06-27 14:21 UTC, gmoocto commented on src/client/components/layouts/RechercherSolution/Résultat/RésultatRechercherSolution.module.scss
> +
On veut le faire pour tous les résultats de recherche? (ça me choque pas mais je pose la question au cas où 😄 )

2023-06-27 14:21 UTC, gmoocto commented on src/server/formations-initiales/infra/onisepFormationInitiale.repository.ts
> +			const apiResponse = await this.httpClient.get<ResultatRechercheFormationInitialeApiResponse>('/dataset/5fa591127f501/search');
On peut sortir dans une constante type `ONISEP_FORMATION_INITIALES_DATASET_ID`

2023-06-28 09:07 UTC, suli-octo commented on src/client/components/features/FormationInitiale/Rechercher/RechercherFormationInitiale.test.tsx
> +		});
Yes bien vu, en plus y avait des warning act de RTL à cause de ce test => utilisation de waitFor

2023-06-28 09:14 UTC, suli-octo commented on src/pages/formations-initiales/index.page.test.tsx
>  	it('envoie les analytics de la page', () => {
Je l'ajoute dans le test de la page index :)

2023-06-28 09:31 UTC, suli-octo commented on src/client/components/features/FormationInitiale/Rechercher/RechercherFormationInitiale.tsx
> +					if (response.instance === 'success') {
yes, et y en a d'autres qui sont dans les fichiers tsx, je propose qu'on fasse le changement d'un coup dans une autre PR  ^^

2023-06-28 09:36 UTC, suli-octo commented on src/client/components/features/FormationInitiale/Rechercher/RechercherFormationInitiale.tsx
> +				<li key={formation.libelle}>
Ah yes bien ! mais ça me fait poser la question de quel est l'ID d'une formation initiale, dans la réponse qu'on reçoit, il n'y a pas d'id explicite.

Il y a un champ `"code_nsf": "343"` mais ça me parait léger pour que ce soit un id. 
Sinon on a aussi `"url_et_id_onisep": "http://www.onisep.fr/http/redirection/formation/slug/FOR.1687"` on pourrait récupérer le FOR.1687 mais bon pas à l'abris qu'ils changent leur system ..

2023-06-28 09:38 UTC, suli-octo commented on src/client/components/layouts/RechercherSolution/Résultat/RésultatRechercherSolution.module.scss
> +
Je suis pas passée sur toutes les cartes, je vais demander à Lina ou Laurent au cas où ^^

2023-06-28 09:56 UTC, suli-octo commented on src/client/components/features/FormationInitiale/Rechercher/RechercherFormationInitiale.tsx
> +	const messageResultatRecherche: string | React.ReactElement = useMemo(() => {
Yes j'ai enlevé vestige de copier coller je pense

2023-06-28 09:58 UTC, suli-octo commented on src/pages/formations-initiales/index.page.test.tsx
>  	it('envoie les analytics de la page', () => {
Par contre, il y a un warning act qui est apparu (voir si c'est à cause du ref dans form)

2023-06-28 12:01 UTC, suli-octo commented on src/client/components/layouts/RechercherSolution/Résultat/RésultatRechercherSolution.module.scss
> +
Lina m'a dit oui tous les titres de carte commencent par des majuscules, donc ça ne changera rien

2023-06-28 12:08 UTC, suli-octo commented on src/client/components/features/FormationInitiale/FormulaireRecherche/FormulaireRechercheFormationInitiale.tsx
> +			ref={refRechercheFormationInitiale}
J'ai pas l'impression que ce soit utilisé, et tout fonctionne sans cette ref donc enlevée ✅

2023-06-28 12:33 UTC, Naorid commented on src/client/components/features/FormationInitiale/Rechercher/RechercherFormationInitiale.tsx
> +				<li key={formation.libelle}>
Dans tous les cas on aura besoin du FOR.1687 pour faire des jointures avec les autre db donc on peut prendre celui la je pense 🤷

2023-06-28 13:17 UTC, gmoocto commented on src/client/components/features/FormationInitiale/Rechercher/RechercherFormationInitiale.tsx
> +				<li key={formation.libelle}>
Oui, je pense qu'on pourra l'extraire dans notre mapper infra (onisepRepository) -> domaine et avoir un champ `id` ou `id_onisep`

2023-06-28 13:21 UTC, gmoocto approved these changes

2023-06-29 07:40 UTC, merged