Feat/unj1s 1577 afficher les tags dans les cartes
DNUM-SocialGouv/1j1s-front pull request #1584
Opened 2023-07-05 13:54 UTC by Nofe18

2023-07-06 07:58 UTC, juliebrunetto83 commented on src/client/components/features/FormationInitiale/Rechercher/RechercherFormationInitiale.test.tsx
> +	describe('Lorsque je fais une recherche de formation initale', () => {
initiale *

2023-07-06 07:59 UTC, juliebrunetto83 commented on src/client/components/features/FormationInitiale/Rechercher/RechercherFormationInitiale.test.tsx
> +			it('Les cards affichent des taqs',  async ()=> {
tags*

2023-07-06 08:00 UTC, juliebrunetto83 commented on src/client/components/features/FormationInitiale/Rechercher/RechercherFormationInitiale.test.tsx
> +				const formationInitialTags=[formationInitiale.duree,formationInitiale.niveauDeCertification,formationInitiale.niveauDeSortieIndicatif];
Initiale*

2023-07-06 08:03 UTC, juliebrunetto83 commented on src/client/components/features/FormationInitiale/Rechercher/RechercherFormationInitiale.tsx
> +						étiquetteOffreList={[formation.duree, formation.niveauDeCertification !='0' || '' ? 'Certifiante' : '', formation.niveauDeSortieIndicatif]}
Est ce que tu peux l'extraire dans une fonction ? pour plus de lisibilité

2023-07-06 08:04 UTC, juliebrunetto83 commented on src/client/services/formationInitiale/formationInitiale.service.fixture.ts
> +		duree:'1 an',
problème d'espace

2023-07-06 08:04 UTC, juliebrunetto83 commented on src/client/services/formationInitiale/formationInitiale.service.fixture.ts
> +
tu peux supprimer les lignes vides ?

2023-07-06 08:10 UTC, juliebrunetto83 commented on src/client/services/formationInitiale/formationInitiale.service.fixture.ts
> +export function aFormationInitiale(override?: Partial<FormationInitiale>): FormationInitiale {
Pourquoi ce renommage ?

2023-07-06 08:27 UTC, juliebrunetto83 commented on src/client/services/formationInitiale/formationInitiale.service.fixture.ts
> +export function aFormationInitiale(override?: Partial<FormationInitiale>): FormationInitiale {
je l'aurai plutot appelé aResultatFormationInitiale pour le distinguer de la fixture du server

2023-07-06 08:52 UTC, juliebrunetto83 commented on src/client/components/features/FormationInitiale/Rechercher/RechercherFormationInitiale.test.tsx
> +				cardTitles.forEach((item)=>{
Je te propose cette implémentation, ce test veut checker le nombre de carte visible, c'est un peu dommage de prendre le cas particulier de 1 carte et le fait de faire un 'forEach' sur une liste de 1 élément c'est pas l'idéal 
Dis moi ce que tu en penses :) ?

`			it('lorsqu‘il y a des résultats doit affiché le bon nombre de cards', async () => {
				const aFormationService = aFormationInitialeService();
				const resultRechercheFormation = createSuccess([aFormationInitiale({ libelle: 'boulanger' }), aFormationInitiale({ libelle: 'patissier' })]);
				jest.spyOn(aFormationService, 'rechercherFormationInitiale').mockResolvedValueOnce(resultRechercheFormation);
				render(<DependenciesProvider formationInitialeService={aFormationService}>
					<RechercherFormationInitiale/>
				</DependenciesProvider>,
				);
				const listeCards = await screen.findByRole('list', { name: 'Formations Initiales' });
				const cardTitles = within(listeCards).getAllByRole('heading', { level: 3 });
				expect(cardTitles).toHaveLength(2);
				expect(cardTitles[0]).toBeVisible();
				expect(cardTitles[0]).toHaveTextContent('boulanger');
				expect(cardTitles[1]).toBeVisible();
				expect(cardTitles[1]).toHaveTextContent('patissier');
			});`

2023-07-06 09:21 UTC, juliebrunetto83 commented on src/server/formations-initiales/infra/onisepFormationInitiale.repository.ts
> +			const formationsInitiales:FormationInitiale[] = formationsInitialesApiResponse.map((formationInitialeApiResponse) => ({
Est ce que tu peux extraire le map dans une fonction ?

2023-07-06 09:24 UTC, juliebrunetto83 commented on src/client/components/features/FormationInitiale/Rechercher/RechercherFormationInitiale.tsx
> +						étiquetteOffreList={[formation.duree, formation.niveauDeCertification !='0' || '' ? 'Certifiante' : '', formation.niveauDeSortieIndicatif]}
Ah mais non je viens de penser ça doit être construit côté BFF ça :)

2023-07-07 07:13 UTC, juliebrunetto83 requested changes
On voit ensemble pour les derniers changements :)

2023-07-07 15:48 UTC, Nofe18 commented
Il restera les soucis d'espace.

2023-07-10 12:36 UTC, gmoocto commented on src/client/components/features/FormationInitiale/Rechercher/RechercherFormationInitiale.test.tsx
> +					expect(await screen.findByText(/[0-9]+ formations pour boulanger/)).toBeVisible();
nitpick: comme on a pas de test qui vérifie que le nombre de formations correspond bien au nombre de résultats dans la liste, on aurait pu mettre : 
```suggestion
					expect(await screen.findByText(/2 formations pour boulanger/)).toBeVisible();
```

2023-07-10 12:39 UTC, gmoocto commented on src/client/components/features/FormationInitiale/Rechercher/RechercherFormationInitiale.test.tsx
> +				it('je vois les tags', async () => {
C'est le même test qu'au dessus non? 🤔

2023-07-10 12:57 UTC, juliebrunetto83 commented on src/client/components/features/FormationInitiale/Rechercher/RechercherFormationInitiale.test.tsx
> +				it('je vois les tags', async () => {
oui totalement ..... j'ai corrigé :) merci !

2023-07-10 13:17 UTC, juliebrunetto83 approved these changes

2023-07-10 13:23 UTC, merged