feat(formation-init): Consulter le detail dune formation carte onisep
DNUM-SocialGouv/1j1s-front pull request #1709
Opened 2023-07-31 09:34 UTC by suli-octo

2023-07-31 13:56 UTC, suli-octo commented on src/client/components/features/ServiceCard/Card/ServiceCard.module.scss
Les changements sur ce fichier ne sont pas directement liés au ticket, BSR pour prendre les changements UI sur les cartes des partenaires (Cf UI kit https://www.figma.com/file/8N2OmFVErgKMwNkiYX8hg3/UI-Kit---1jeune1solution?type=design&node-id=10602-7718&mode=design&t=p2lqoDsqxFocOOuh-0)

2023-07-31 13:56 UTC, suli-octo commented on src/client/components/layouts/ConsulterOffre/ConsulterOffreLayout.module.scss
idem, BSR + fix espacement

2023-07-31 15:55 UTC, gmoocto requested changes

2023-07-31 15:55 UTC, gmoocto commented on src/client/components/features/FormationInitiale/ConsulterDetail/ConsulterDetailFormationInitiale.tsx
> +	}
suggestion: On pourrait déplacer cette méthode à côté de la définition du type

2023-07-31 15:55 UTC, gmoocto commented on src/client/components/features/ServiceCard/Card/ServiceCard.module.scss
> +      @include utilities-deprecated.media(large) {
```suggestion
      @include utilities.media(large) {
```

2023-07-31 15:55 UTC, gmoocto commented on src/client/components/features/ServiceCard/OnisepGeneralPartner.tsx
> +	headingLevel?: HtmlHeadingTag
Est-ce qu'on le rend obligatoire du coup? 😛

2023-07-31 15:55 UTC, gmoocto commented on src/client/components/layouts/ConsulterOffre/ConsulterOffreLayout.module.scss
> +    @include utilities-deprecated.media(xlarge) {
```suggestion
    @include utilities.media(xlarge) {
```

2023-07-31 15:55 UTC, gmoocto commented on src/pages/formations-initiales/[id].module.scss
> +  @include utilities-deprecated.media(xlarge) {
```suggestion
  @include utilities.media(xlarge) {
```

2023-07-31 15:55 UTC, gmoocto commented on src/pages/formations-initiales/[id].module.scss
> +    color: utilities.$color-primary;
Est-ce qu'on wrap dans une variable? 😇

2023-07-31 15:55 UTC, gmoocto commented on src/server/cms/infra/repositories/strapi.mapper.ts
> +		updatedAt: formationInitiale.updatedAt,
nitpick: Pour ne pas avoir dans l'anglais dans notre domain 😬
```suggestion
		dateDeMiseAJour: formationInitiale.updatedAt,
```

2023-07-31 15:55 UTC, gmoocto commented on src/pages/formations-initiales/[id].page.test.tsx
> +			jest.spyOn(Date.prototype, 'toLocaleDateString').mockReturnValue(todayDate);
On ne voudrait pas stubber `formatToFRLongDate` directement?

2023-08-01 09:39 UTC, suli-octo commented on src/client/components/features/ServiceCard/OnisepGeneralPartner.tsx
> +	headingLevel?: HtmlHeadingTag
on peut yes ^^

2023-08-01 15:49 UTC, gmoocto commented on src/client/services/date/js/js.date.service.test.ts
> + */
On peut supprimer ça normalement pour que les tests tournent plus vite (pas besoin du dom ici)

2023-08-01 16:28 UTC, merged