fix(sentry): un minifying sentry pas dinformation sur les erreurs front
DNUM-SocialGouv/1j1s-front pull request #1758
Opened 2023-08-07 08:46 UTC by suli-octo

2023-08-07 12:43 UTC, suli-octo commented
TODO: ajouter une var d'env SENTRY_RELEASE, dont la valeur est reprend ce qu'il y avait avant dans le fichier de config: `${name}@${version}-${RELEASE_NAME_SUFFIX}`.
La version de la release est disponible dans le package.json, possible de la récupérer et de la mettre à jour de façon dynamique avant le déploiement terraform en suivant https://cli.github.com/manual/gh_variable_set ? (à investiguer)

2023-08-18 08:03 UTC, Mintoo200 requested changes

2023-08-18 08:03 UTC, Mintoo200 commented on next.config.js
> +	disableServerWebpackPlugin: false, // TODO SULI : une fois que le fix est validé en recette, avant de mettre en prod, remettre les valeurs d'avant
tu peux faire un déploiement en recette sans merger pour vérifier comme ça tu peux le repasser à la bonne valeur avant de merger

2023-08-18 08:03 UTC, Mintoo200 commented on sentry.client.config.ts
> +// };
👉 🗑️

2023-08-18 14:23 UTC, Mintoo200 approved these changes

2023-08-18 14:30 UTC, merged