feat(formation-init): prendre en compte le html dans l'affichage de la description
DNUM-SocialGouv/1j1s-front pull request #1841
Opened 2023-08-21 10:06 UTC by suli-octo

2023-08-21 13:13 UTC, juliebrunetto83 commented on src/client/components/features/FormationInitiale/ConsulterDetail/ConsulterDetailFormationInitiale.module.scss
> -  display: grid;
Pourquoi avoir enlevé l'utilisation de grid pour du flex ?

2023-08-21 13:34 UTC, juliebrunetto83 commented on src/client/hooks/useSanitize.test.tsx
> +function setupUseSanitize(dirtyContent?: string, shouldReplaceCarriageReturn?: boolean): string {
oh c'est malin, l'objectif c'est de pouvoir tester lorsque tu as un hook ?

2023-08-21 13:36 UTC, juliebrunetto83 commented on src/client/components/layouts/ConsulterOffre/ConsulterOffreLayout.module.scss
> -    section {
ça impact tous les détails, tu as check qu'il n'y avait pas de comportement non voulu sur les autres pages ?

2023-08-21 13:38 UTC, juliebrunetto83 commented on src/client/components/features/FormationInitiale/ConsulterDetail/ConsulterDetailFormationInitiale.tsx
> +	const poursuiteEtudesDirty= isFormationWithDetails(formationInitialeDetail) ? formationInitialeDetail.poursuiteEtudes : undefined;
tu peux faire un petit option command L ? il manque des espaces ?

2023-08-21 13:42 UTC, juliebrunetto83 commented on src/client/components/features/FormationInitiale/ConsulterDetail/ConsulterDetailFormationInitiale.tsx
> +	const descriptionDirty= isFormationWithDetails(formationInitialeDetail) ? formationInitialeDetail.description : undefined;
je comprends pas l'utilité des isFormationWithDetails ? au pire il n'y a pas le détail complet et la valeur est à undefined ?

2023-08-21 13:47 UTC, juliebrunetto83 commented on src/client/components/features/FormationInitiale/ConsulterDetail/ConsulterDetailFormationInitiale.tsx
> +	const descriptionDirty= isFormationWithDetails(formationInitialeDetail) ? formationInitialeDetail.description : undefined;
Pour éviter d'appeler 4 fois la fonction isFormationWithDetails ? 
`const isFormationInitialeWithCMSDetails = isFormationWithDetails(formationInitialeDetail);
	
	const descriptionDirty= isFormationInitialeWithCMSDetails ? formationInitialeDetail .description: undefined;
	const attendusParcoursupDirty = isFormationInitialeWithCMSDetails ? formationInitialeDetail.attendusParcoursup : undefined;
	const conditionsAccesDirty= isFormationInitialeWithCMSDetails ? formationInitialeDetail.conditionsAcces : undefined;
	const poursuiteEtudesDirty= isFormationInitialeWithCMSDetails ? formationInitialeDetail.poursuiteEtudes : undefined;`

2023-08-21 13:50 UTC, juliebrunetto83 requested changes
En attendant la modif avec le useSanitize 😁

2023-08-21 14:01 UTC, suli-octo commented on src/client/hooks/useSanitize.test.tsx
> +function setupUseSanitize(dirtyContent?: string, shouldReplaceCarriageReturn?: boolean): string {
Yes ! comme ça on peut tester des hooks en isolation sans passer par un composant

2023-08-21 14:04 UTC, suli-octo commented on src/client/components/layouts/ConsulterOffre/ConsulterOffreLayout.module.scss
> -    section {
oui j'ai vérifié le padding est assuré par `.layoutContainer {
    width: 100%;
    padding: 0 1rem;` (ligne 10) 

On avait des paddings en doubles les padding sur section

2023-08-21 14:06 UTC, suli-octo commented on src/client/components/features/FormationInitiale/ConsulterDetail/ConsulterDetailFormationInitiale.tsx
> +	const descriptionDirty= isFormationWithDetails(formationInitialeDetail) ? formationInitialeDetail.description : undefined;
yes! bien vu !

2023-08-22 07:33 UTC, juliebrunetto83 commented on src/client/components/features/FicheMétier/Rechercher/RésultatRechercherMétier.tsx
> +import { formatCarriageReturnToHtml } from '../../../../utils/formatCarriageReturnToHtml';
import relatif :)

2023-08-22 07:35 UTC, juliebrunetto83 approved these changes

2023-08-22 08:12 UTC, merged