feat(offre): validation api pole emploi
DNUM-SocialGouv/1j1s-front pull request #1901
Opened 2023-08-29 16:28 UTC by Naorid

2023-08-31 08:45 UTC, juliebrunetto83 commented on src/server/emplois/infra/repositories/apiPoleEmploiOffre.repository.test.ts
> +		describe('lorsqu‘il y a une erreur de validation', () => {
' erreur de validation de l'api '

2023-08-31 08:46 UTC, juliebrunetto83 commented on src/server/emplois/infra/repositories/apiPoleEmploiOffre.repository.test.ts
> +		describe('lorsqu‘il y a une erreur de validation', () => {
'de l'api'

2023-08-31 08:49 UTC, juliebrunetto83 commented on src/server/emplois/infra/repositories/apiPoleEmploiOffre.repository.ts
> +			for (const offre of response.data.resultats) {
pourquoi tu es obligé de faire une boucle ? tu peux pas le mettre dans le schéma que c'est un array ?

2023-08-31 15:14 UTC, Naorid commented on src/server/emplois/infra/repositories/apiPoleEmploiOffre.repository.ts
> +			for (const offre of response.data.resultats) {
Ca me permet d'avoir que 1 schema que je peux utiliser pour la recherche et le detail. A part que c'est un peu moins optimisé je vois pas trop de raison de faire 2 schema perso 🤔

2023-09-01 15:13 UTC, juliebrunetto83 requested changes
en attente du jardinageee

2023-10-12 08:27 UTC, gmoocto approved these changes

2023-10-23 15:13 UTC, merged