feat(UI): mise à jour des tags au kit UI
DNUM-SocialGouv/1j1s-front pull request #1905
Opened 2023-08-31 07:55 UTC by juliebrunetto83

2023-09-01 07:25 UTC, gmoocto commented on src/client/components/ui/Meilisearch/MeilisearchCustomCurrentRefinements.tsx
> +							</button>
Juste un petit souci avec l'`aria-label` ->
Comme il est sur le bouton, il va prendre le dessus sur le contenu qui est à l'intérieur. Ce qui sera vocalisé sera uniquement "supprimer le filtre" et le label ne sera pas vocalisé. 
On pourrait reprendre le `refinement.label` dans l'aria-label et avoir par exemple : 
```suggestion
							<button aria-label={`${refinement.label} - supprimer le filtre`} type="button" onClick={() => refine(refinement)}>
								{getCapitalizedItems(refinement.label)}
								<Icon name="close" />
							</button>
```


Pour plus d'info sur la manière dont son calculé les noms accessibles, j'ai été fouiller sur : 
https://www.w3.org/WAI/WCAG22/Techniques/aria/ARIA8#:~:text=Per%20the%20Accessible%20Name%20and,text%20supplied%20within%20the%20link. (celui ci concerne le lien mais est assez concis) 
https://www.w3.org/TR/accname/#terminology (celui ci est complet mais assez indigeste 😄 )

2023-09-01 08:15 UTC, gmoocto commented on src/client/components/ui/Tag/Tag.module.scss
> +  }
nitpick: j'aurais bien "ventilé" deux  `utilities.media(large)` dans le selecteur du dessus, pour avoir les redéfinitions des propriétés au plus près des déclarations originales 

Ex: 

```scss
.tag {
  [...]
  padding: 0.25rem 0.5rem;
  border-radius: 2rem;
  @include utilities.media(large) {
    padding: 0.5rem 0.75rem;
  }
  [...]
```

Ça me permet de voir que la redefinition du `border-radius` est surement superflue

2023-09-01 08:16 UTC, gmoocto requested changes
(commentaire aria-label + nitpick)

2023-09-01 09:07 UTC, juliebrunetto83 commented on src/client/components/ui/Tag/Tag.module.scss
> +  }
Je crois que dans l'un des premiers jardinage tech on avait décidé de regrouper les propriétés utilisé dans les `@include utilities.media(large) ` en bas des fichiers

A voir si souhaite changer :)

Par contre bien vu pour le border-radius je change !

2023-09-04 06:24 UTC, gmoocto approved these changes

2023-09-05 07:23 UTC, merged