feat(europe): recherche emplois en europe
DNUM-SocialGouv/1j1s-front pull request #2061
Opened 2023-09-28 08:51 UTC by Naorid

2023-09-29 15:41 UTC, Naorid commented on .env.test
> +API_EURES_IS_MOCK_ACTIVE=0
Utilisé temporairement pour le developpement. Si actif, on utilise fixtureEmploiEuropeRepository

2023-10-02 09:01 UTC, gmoocto commented on .env.scalingo
> +API_EURES_BASE_URL=https://webgate.acceptance.ec.europa.eu/eures-api/output/api/v1/jv/
Attention, il faut ajouter les refs aux variables d'environnement ici, pas la valeur directement

2023-10-02 09:01 UTC, gmoocto commented on .env.scalingo
> +API_EURES_IS_MOCK_ACTIVE=0
Attention, il faut ajouter les refs aux variables d'environnement ici, pas la valeur directement

2023-10-02 10:06 UTC, gmoocto requested changes

2023-10-02 10:06 UTC, gmoocto commented on src/server/emplois-europe/infra/repositories/apiEuresEmploiEurope.repository.test.ts
> +				expect(httpClientService.post).toHaveBeenCalledWith('/search', body);
Petit souci ici : 
Si je modifie la fonction `anApiEuresRechercheBody();` pour remplacer "boulanger" par "instituteur", le test passera au rouge alors que la fonction remplie toujours son "contrat" (= renvoyer un `ApiEuresRechercheBody` )

Dans ce cas là, je suis plutôt reprendre tout ou partie du body dans le test (comme en dessous) même si c'est verbeux

2023-10-02 10:06 UTC, gmoocto commented on src/server/emplois-europe/infra/repositories/apiEuresEmploiEurope.repository.ts
> +	private static buildSearchBody(filtre: EmploiEuropeFiltre) {
On peut creer un type `ApiEuresRechercheBody` qu'on peut utiliser ici + dans `anApiEuresRechercheBody`

2023-10-02 10:06 UTC, gmoocto commented on src/client/components/features/EmploisEurope/Rechercher/RechercherEmploisEurope.test.tsx
> +});
J'ai rien dit, ils sont plus déjà existants

2023-10-02 12:40 UTC, Naorid commented on src/client/components/features/EmploisEurope/FormulaireRecherche/FormulaireRechercheEmploisEurope.tsx
> +	from '~/client/components/features/Alternance/Rechercher/FormulaireRecherche/FormulaireRechercheAlternance.module.scss';
😭

2023-10-02 12:49 UTC, Naorid commented on src/client/components/features/EmploisEurope/Rechercher/RechercherEmploisEurope.tsx
> +				messageRésultatRecherche={''}
Il est ajouté dans la PR juste apres avec le nombre d'elements 😅

2023-10-02 12:50 UTC, Naorid commented on src/pages/emplois-europe/index.page.test.tsx
>  				</DependenciesProvider>);
Par défaut y'a pas de resultats de recherche, est ce qu'il faudrait faire un parcour utilisateur pour vraiment tester la page ?

2023-10-02 12:58 UTC, Naorid commented on src/pages/emplois-europe/index.page.test.tsx
>  				</DependenciesProvider>);
TODO : Utiliser les query params

2023-10-02 13:35 UTC, gmoocto approved these changes

2023-10-02 13:48 UTC, merged