fix(multiple): unification regex email front-back
DNUM-SocialGouv/1j1s-front pull request #2249
Opened 2023-11-02 15:11 UTC by Naorid

2023-11-06 07:31 UTC, juliebrunetto83 commented on src/shared/emailRegex.ts
> +export const emailRegex = /^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/;
En voyant les deux constantes j'ai du mal à comprendre qui sert à quoi, est ce qu'on peut trouver un nom plus explicite ?

2023-11-06 07:35 UTC, juliebrunetto83 commented on src/shared/emailRegex.ts
> +export const emailRegex = /^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/;
Je trouve ça aussi un peu étrange d'avoir un ficher commun au bff et au 'front'

2023-11-06 07:35 UTC, juliebrunetto83 commented on src/client/components/ui/Form/InputText/InputText.test.tsx
> +			it('ne contient pas d\'attribut aria-errormessage quand le message d\'erreur n\'est pas présent', () => {
‘

2023-11-06 07:40 UTC, juliebrunetto83 commented on src/client/components/ui/Form/InputText/InputText.test.tsx
> +			it('ne contient pas d\'attribut aria-errormessage quand le message d\'erreur n\'est pas présent', () => {
Je n'ai pas compris l'interet de ce test

2023-11-06 07:42 UTC, juliebrunetto83 requested changes
partante pour en rediscuter !

2023-11-07 09:03 UTC, Naorid commented on src/shared/emailRegex.ts
> +export const emailRegexHTML = '^[a-zA-Z0-9.!#$%&’*+\\/=?^_`\\{\\|\\}~\\-]+@[a-zA-Z0-9\\-]+(?:.[a-zA-Z0-9\\-]+)*$';
emailRegexStringFormat

2023-11-07 09:30 UTC, juliebrunetto83 approved these changes

2023-11-14 08:37 UTC, merged