refactor: cypress testing library formulaire depot stage
DNUM-SocialGouv/1j1s-front pull request #2262
Opened 2023-11-06 16:41 UTC by Mintoo200

2023-11-07 09:21 UTC, juliebrunetto83 commented on cypress/e2e/formulaire_depot_stage.cy.ts
> +				// FIXME (GAFI 06-11-2023): Manque un accent sur le "E"
Pourquoi tu ne l'as pas fix ?

2023-11-07 09:23 UTC, juliebrunetto83 commented on cypress/e2e/formulaire_depot_stage.cy.ts
> +				//	Also besoin de type 2x parce que la lib est cassée
Whaaaat ?

2023-11-07 09:29 UTC, juliebrunetto83 commented on src/client/components/features/OffreDeStage/Déposer/StageDeposerOffre.fixture.ts
> +export const aFormulaireEtapeLocalisation = () => {
Pourquoi avoir enlevé le type ?

2023-11-07 09:29 UTC, juliebrunetto83 requested changes
Je mets en request change pour discuter des coms

2023-11-07 13:55 UTC, Mintoo200 commented on src/client/components/features/OffreDeStage/Déposer/StageDeposerOffre.fixture.ts
> +export const aFormulaireEtapeLocalisation = () => {
Je vais plutôt inliner les textes dans les inputs plutôt que de passer par la fixture

2023-11-20 15:16 UTC, Mintoo200 commented on cypress/e2e/formulaire_depot_stage.cy.ts
> +				// FIXME (GAFI 06-11-2023): Manque un accent sur le "E"
Fix dans la PR #2333 parce que c'était pas que à cet endroit, j'ai fait un gros _Find & Replace_. Il faut merge cette PR pour pouvoir facilement review la suivante donc si c'est OK pour toi, go Merge celle-là, je rebase celle pour les accents et on peut review et merge rapidement l'autre

2023-11-20 15:49 UTC, Mintoo200 commented on src/client/components/features/OffreDeStage/Déposer/StageDeposerOffre.fixture.ts
> +export const aFormulaireEtapeLocalisation = () => {
En fait je me rends compte que c'est des fixtures spécifiques pour remplir le formulaire, c'est pas celles associées aux objets métiers donc c'est bien le typage qui n'est pas bon. Par contre du coup je vais supprimer tous les typages du fichier puisque ces fixtures ne devraient pas être associées aux objets métier du back

2023-11-21 16:14 UTC, juliebrunetto83 approved these changes

2023-11-21 16:15 UTC, merged