fix(multiple): le bouton retour apparait tout le temps
DNUM-SocialGouv/1j1s-front pull request #2324
Opened 2023-11-17 16:22 UTC by Naorid

2023-11-21 14:00 UTC, gmoocto commented on src/client/components/layouts/Error/ErrorLayout.tsx
> +					<BackButton alwaysDisplay={true} aria-label="Retourner à la page précédente" label="Retourner à la page précédente" appearance="primary" className={styles.backButton}/>
À la lecture du code, j'ai un peu de mal à voir pourquoi on a besoin d'un `alwaysDisplay` 🤔

2023-11-21 15:27 UTC, Naorid commented on src/client/components/layouts/Error/ErrorLayout.tsx
> +					<BackButton alwaysDisplay={true} aria-label="Retourner à la page précédente" label="Retourner à la page précédente" appearance="primary" className={styles.backButton}/>
Pour la page d'erreur je trouvais ca pertinent d'avoir tout le temps le bouton 🤷

2023-11-22 16:25 UTC, gmoocto requested changes
Enlever le alwaysDIsplay

2023-11-24 08:48 UTC, gmoocto approved these changes

2023-11-24 09:42 UTC, merged