test: ajouts de html validator - partie 2
DNUM-SocialGouv/1j1s-front pull request #2334
Opened 2023-11-20 15:32 UTC by gmoocto

2023-11-27 09:47 UTC, Mintoo200 requested changes

2023-11-27 09:47 UTC, Mintoo200 commented on src/client/components/ui/Form/InputText/InputText.tsx
> +				</div>
🤔 Je me demande si on a pas besoin d'un petit `aria-describedby` sur l'input pour qu'il annonce le contenu du tooltip sur lecteur d'écran. Mais du coup c'est un peu chiant puisqu'il faut soit pouvoir récupérer d'id du tooltip soit pouvoir lui en donner un

2023-11-27 09:47 UTC, Mintoo200 commented on src/client/components/ui/Form/InputText/InputText.tsx
> +					{tooltip && tooltip}
```suggestion
					{tooltip}
```

2023-11-27 09:47 UTC, Mintoo200 commented on src/pages/apprentissage-entreprises/index.page.test.tsx
> +		mockUseRouter({ query: { page: '1' } });
```suggestion
		mockUseRouter();
```
D'ailleurs ça a l'air d'être pareil sur tous les tests du fichier

2023-11-27 09:47 UTC, Mintoo200 commented on src/pages/articles/[id].page.test.tsx
> +		article = anArticle();
On peut pas l'inliner ?
```tsx
<ConsulterArticlePage article={anArticle()}/>
```
Pour les tests qui testent réellement le contenu de l'article, il faut de toute façon l'instancier dans le test pour pouvoir override des propriétés, et pour les autres ça change rien si ce n'est que ça évite de déclarer une variable vide qu'on rempli ensuite dans le `beforeEach`

2023-11-27 09:47 UTC, Mintoo200 commented on src/pages/emplois-europe/index.page.test.tsx
> +			await user.click(boutonRecherche);
On a pas besoin de cliquer sur rechercher si on mock les queries déjà avec `page=1` si ?

2023-11-27 09:47 UTC, Mintoo200 commented on src/pages/faq/[id].page.test.tsx
> +			<ConsulterArticlePage faqRéponse={faqRéponse   }/>);
```suggestion
			<ConsulterArticlePage faqRéponse={faqRéponse} />);
```

2023-11-30 09:10 UTC, gmoocto commented on src/client/components/ui/Form/InputText/InputText.tsx
> +				</div>
Tu mettrais l'id  sur le bouton ou le contenu du tooltip? (j'ai l'impression que l'idéal serait plutôt le contenu du tooltip mais ça tendrait sans doute un peu vers la réécriture du composant 😄 )

2023-12-12 10:34 UTC, gmoocto commented on src/pages/apprentissage-entreprises/index.page.test.tsx
> +		mockUseRouter({ query: { page: '1' } });
On pouvait même le virer d'ailleurs

2023-12-12 10:37 UTC, gmoocto commented on src/pages/emplois-europe/index.page.test.tsx
> +			await user.click(boutonRecherche);
C'était pour être sûr d'avoir la recherche terminée avant de passer à la suite, comme le await du `user.click` attend la fin des actions déclenchées

2023-12-12 10:38 UTC, gmoocto commented on src/pages/articles/[id].page.test.tsx
> +		article = anArticle();
Carrément !

2023-12-13 09:25 UTC, Mintoo200 approved these changes

2023-12-13 14:09 UTC, merged