feat: rendre focus visible pour redirections playstore
DNUM-SocialGouv/1j1s-front pull request #2341
Opened 2023-11-21 11:11 UTC by ranaMara8

2023-11-21 14:47 UTC, gmoocto commented on src/client/components/features/ContratEngagementJeune/Application/Application.tsx
> +			<div className={styles.applicationContainer} tabIndex={0}>
On peut supprimer le `tabIndex` :)

A moins qu'il y ait une raison particulière pour laquelle il a été ajouté ?

2023-11-21 15:44 UTC, ranaMara8 commented on src/client/components/features/ContratEngagementJeune/Application/Application.tsx
> +			<div className={styles.applicationContainer} tabIndex={0}>
car le focus n'apparaît pas si nous avons levé tabIndex

2023-11-24 09:01 UTC, gmoocto commented on src/client/components/features/ContratEngagementJeune/Application/Application.tsx
> +			<div className={styles.applicationContainer} tabIndex={0}>
Ah, pas besoin de rendre la div focusable avec tabindex, comme ce n'est pas un élément interactif -> c'était  seulement la visibilité du focus sur les Link qui était à améliorer :)

2023-11-24 10:29 UTC, gmoocto commented on src/client/components/features/ContratEngagementJeune/Application/Application.module.scss
> +    }
Du coup, on peut supprimer ce selecteur

2023-11-24 12:38 UTC, gmoocto commented on src/client/components/features/ContratEngagementJeune/Application/Application.module.scss
> +        outline: 2px solid utilities-deprecated.$color-primary;
Et je me rends compte que c'est les `utilities-deprecated` qui sont utilisé ici 
Le fichier n'a pas encore transitionné mais on peut faire un `@use "@styles/utilities";`  et utiliser les nouvelles couleurs :)

2023-11-27 09:05 UTC, gmoocto approved these changes

2023-11-29 11:04 UTC, gmoocto commented on src/client/components/ui/Accordion/Accordion.module.scss
> +    }
On a déjà un indicateur de focus sur cet élément (et sur les liens aussi normalement) : 
J'ai remarqué que c'était le `overflow: hidden` sur l'élément `section` qui bloquait le bon affichage 

J'ai l'impression que son seul intérêt est de bloquer une superposition d'effet d'ombre (sur le summary + sur la section) 
Il faudrait qu'on valide avec Joy si il ne vaudrait pas mieux mettre un shadow sur l'ensemble du `details` (et pas seulement sur le `summary`) pour obtenir le même effet. (Et nous permettre de supprimer la shadow sur la section ainsi que l'overflow hidden)

2023-11-30 08:35 UTC, gmoocto requested changes
c.f. chose à voir avec Joy

2023-12-11 08:17 UTC, gmoocto approved these changes

2023-12-11 08:29 UTC, merged