feat(stage3eme): recherche
DNUM-SocialGouv/1j1s-front pull request #2350
Opened 2023-11-22 13:58 UTC by Naorid

2023-11-24 16:26 UTC, juliebrunetto83 commented on src/client/components/features/Stages3eme/Rechercher/RechercherStages3eme.test.tsx
> +			const resultatsUl = await screen.findAllByRole('list', { name: 'Stages de 3ème' });
Ul ?

2023-11-24 16:30 UTC, juliebrunetto83 commented on src/client/components/features/Stages3eme/Rechercher/RechercherStages3eme.test.tsx
> +			const resultats = await within(resultatsUl[0]).findAllByTestId('RésultatRechercherSolution');
le testId 😭 pourquoi pas faire `getAllByRole("listitem")`

2023-11-24 16:33 UTC, juliebrunetto83 commented on src/client/components/features/Stages3eme/FormulaireRecherche/ListeResultatsStage3eme.tsx
> +					<p>{stage3eme.adresse.ligne}, {stage3eme.adresse.codePostal} {stage3eme.adresse.ville}</p>
adresse.ligne ? c'est pas très explicite je trouve

2023-11-24 16:37 UTC, juliebrunetto83 commented on src/pages/stages-3eme/index.page.test.tsx
> +			await screen.findByRole('heading', { name: 'Des milliers d’entreprises prêtes à vous accueillir pour votre stage de 3ème' });
pourquoi tu as besoin d'await ici ?

2023-11-24 16:43 UTC, juliebrunetto83 commented on src/server/stage-3eme/infra/repositories/apiImmersionFacileStage3eme.repository.test.ts
> +				jest.spyOn(httpClientService, 'get').mockResolvedValue(anAxiosResponse([anApiImmersionFacileStage3eme(
pourquoi anAxiosResponse et pas createSuccess(...)?

2023-11-24 16:43 UTC, juliebrunetto83 commented on src/server/stage-3eme/infra/repositories/apiImmersionFacileStage3eme.repository.test.ts
> +				jest.spyOn(httpClientService, 'get').mockResolvedValue(anAxiosResponse([anApiImmersionFacileStage3eme(
ça permettrait d'enlever le `as Success<ResultatRechercheStage3eme>;`

2023-11-24 16:48 UTC, juliebrunetto83 commented on src/client/components/features/Stages3eme/Rechercher/RechercherStages3eme.tsx
> +				if (response.instance === 'success') {
isSuccess

2023-11-24 16:51 UTC, juliebrunetto83 commented on src/client/components/features/Stages3eme/Rechercher/RechercherStages3eme.test.tsx
> +	});
Il y a pas du tout de test sur le nombre de résultat c'est dommage

2023-11-24 16:52 UTC, juliebrunetto83 requested changes
:)

2023-11-27 09:16 UTC, Naorid commented on src/client/components/features/Stages3eme/FormulaireRecherche/ListeResultatsStage3eme.tsx
> +					<p>{stage3eme.adresse.ligne}, {stage3eme.adresse.codePostal} {stage3eme.adresse.ville}</p>
Pour moi c'est comme ca qu'on appelle "1 rue de la liberté". Y'a d'autre endroits ou on avait mis adresse.adresse et je trouvais ca moyen 🤔

2023-11-27 09:17 UTC, Naorid commented on src/pages/stages-3eme/index.page.test.tsx
> +			await screen.findByRole('heading', { name: 'Des milliers d’entreprises prêtes à vous accueillir pour votre stage de 3ème' });
J'avais un act() apres le render

2023-11-27 09:20 UTC, Naorid commented on src/server/stage-3eme/infra/repositories/apiImmersionFacileStage3eme.repository.test.ts
> +				jest.spyOn(httpClientService, 'get').mockResolvedValue(anAxiosResponse([anApiImmersionFacileStage3eme(
hmmmmm
Le httpClientService.get retourne une axiosResponse (c'est pour ca qu'on met un catch pour chopper les AxiosError.
C'est le repository qui retourne un Either. Le as Success je le mets que pour eviter de faire un if isSuccess et gagner une ou deux lignes

2023-11-27 09:44 UTC, Naorid commented on src/client/components/features/Stages3eme/Rechercher/RechercherStages3eme.test.tsx
> +			const resultats = await within(resultatsUl[0]).findAllByTestId('RésultatRechercherSolution');
On peut pas faire ca parce que les tags dans les cartes ont aussi des li donc ca casserait le compte.
J'ai remplacé par un resultatsUl.children mais je dois mettre un es-lint ignore :/

2023-11-28 08:18 UTC, juliebrunetto83 commented on src/client/components/features/Stages3eme/Rechercher/RechercherStages3eme.test.tsx
> +			const resultatsUl = await screen.findAllByRole('list', { name: 'Stages de 3ème' });
listResultats serait mieux je pense

2023-11-28 08:53 UTC, juliebrunetto83 commented on src/client/components/features/Stages3eme/Rechercher/RechercherStages3eme.test.tsx
> +			const resultats = await within(resultatsUl[0]).findAllByTestId('RésultatRechercherSolution');
effectivement c'est bien dommage

2023-11-28 08:54 UTC, juliebrunetto83 commented on src/client/components/features/Stages3eme/Rechercher/RechercherStages3eme.test.tsx
> +			const resultats = await within(resultatsUl[0]).findAllByTestId('RésultatRechercherSolution');
par contre le await de la ligne 65 ne devrait pas servir `within(resultatsUl[0]).getAllByTestId('RésultatRechercherSolution');`

2023-11-28 08:55 UTC, juliebrunetto83 commented on src/client/components/features/Stages3eme/FormulaireRecherche/ListeResultatsStage3eme.tsx
> +					<p>{stage3eme.adresse.ligne}, {stage3eme.adresse.codePostal} {stage3eme.adresse.ville}</p>
je préfère adresse.adresse perso, c'est comme ça que j'appelle une adresse 😛

2023-11-28 08:59 UTC, juliebrunetto83 commented on src/server/stage-3eme/infra/repositories/apiImmersionFacileStage3eme.repository.test.ts
> +				jest.spyOn(httpClientService, 'get').mockResolvedValue(anAxiosResponse([anApiImmersionFacileStage3eme(
ah c'est "rigolo" le httpClientService renvoie un success/error mais pas le publicHttpClientService

2023-11-28 09:03 UTC, juliebrunetto83 commented on src/server/stage-3eme/infra/repositories/apiImmersionFacileStage3eme.repository.test.ts
> +				jest.spyOn(httpClientService, 'get').mockResolvedValue(anAxiosResponse([anApiImmersionFacileStage3eme(
c'est plus sympa comme ça `	expect(result).toEqual({
					instance: 'success', result: aResultatRechercheStage3eme({
						nombreDeResultats: 1,
						resultats: [
							{
								adresse: {
									codeDepartement: '75',
									codePostal: '75001',
									ligne: '1 Rue de la Lune',
									ville: 'Paris',
								},
								domaine: 'Boulangerie',
								nomEntreprise: 'La Boulangerie',
							},
						],
					}),
				});`
				
				Au moins tu test que c'est bien un success et que le résultat est celui attendu

2023-11-28 09:05 UTC, juliebrunetto83 approved these changes

2023-11-28 09:30 UTC, Naorid commented on src/client/components/features/Stages3eme/FormulaireRecherche/ListeResultatsStage3eme.tsx
> +					<p>{stage3eme.adresse.ligne}, {stage3eme.adresse.codePostal} {stage3eme.adresse.ville}</p>
ah ouais d'accord 🙄

2023-11-28 09:41 UTC, Naorid commented on src/client/components/features/Stages3eme/Rechercher/RechercherStages3eme.test.tsx
> +			const resultats = await within(resultatsUl[0]).findAllByTestId('RésultatRechercherSolution');
il existe plus 🤷

2023-11-28 16:16 UTC, merged