feat: delete dsfr
DNUM-SocialGouv/1j1s-front pull request #240
Opened 2022-08-26 15:22 UTC by AliElAmrani

2022-08-30 12:49 UTC, paulgallocto commented
Je mets tous les commentaires de recette que j'ai vu en me balandant sur la review app :
Page emploi
- le texte de certains placeholders des input n'est pas de la meme font (il manque sans doute un `font-family: inherit`)
- le texte des placeholders des input est un peu trop gros
Detail offre emploi 
- manque une margin bottom sur le h2
Page CEJ
- le titre est cassé
Page Je deviens mentor
- les titres sont cassés
- le texte n'est pas centré (cf les maquettes)

2022-08-30 15:28 UTC, olivocto requested changes

2022-08-30 15:28 UTC, olivocto commented on src/client/components/features/ConsulterOffre.module.scss
> +  border-bottom: 1px solid $color-form-field;
mauvaise variable utilisée ici

2022-08-30 15:28 UTC, olivocto commented on src/client/components/features/Engagement/FormulaireRecherche/FormulaireRechercheMissionEngagement.module.scss
> +  border-bottom: 1px solid $color-form-field;
idem ici

2022-08-30 15:28 UTC, olivocto commented on src/client/components/features/MesuresJeunes/MesuresJeunes.module.scss
> +    font-weight: 700;
la aussi il existe un placeholder que tu peux @extend

2022-08-30 15:28 UTC, olivocto commented on src/client/components/features/Partner/Card/PartnerCard.module.scss
> -  // TODO: must delete when removing dsfr
alors finalement il va falloir laisser ça, ça pète tout le style sinon. On se fait ça demain

2022-08-30 15:28 UTC, olivocto commented on src/client/components/layouts/ConsulterOffre/ConsulterOffreLayout.module.scss
> +        border: 1px solid $color-disabled;
prendre une autre variable

2022-08-30 15:28 UTC, olivocto commented on src/client/components/layouts/RechercherSolution/Résultat/RésultatRechercherSolution.module.scss
> +  background: $color-on-primary;
ce serait plutôt $color-surface

2022-08-30 16:04 UTC, LiquidITGuy commented
De notre côté les regressions qu'on peut constater : 
les labels au dessus du champs de recherche sur la page stages/index ont changé de design (léger).
Le champs de recherche sur la page stages/index a changé de design (assez voyant)
l'espace sous la pagination de la page stages/index a disparu et les éléments sont trop collés 

les titres, intitulé et employeur (niveau de H) ont sauté sur stages/[slug]
les entêtes de section ont sauté sur stages/[slug]
Les styles liés aux contenus renvoyés dans le cms semblent avoir sauté (exemple : liste à puce non affiché à puce, liens deviennent non soulignés ni stylisés, 
Les sauts de lignes/paragraphes ne semblent plus pris en compte
on a pas pu retester les images on n'a pas retrouvé d'offres qui en avait :s

2022-09-02 10:03 UTC, olivocto approved these changes

2022-09-02 10:04 UTC, merged