tech(logement): sortir du CMS annonce de logement
DNUM-SocialGouv/1j1s-front pull request #2416
Opened 2023-12-05 08:32 UTC by suli-octo

(WIP : s'occuper du…namespace AnnonceDeLogement qui reste dans collection Strapi)

2023-12-05 14:07 UTC, juliebrunetto83 commented on src/server/logements/infra/strapiAnnonceDeLogement.repository.ts
> +			const slugs = allStrapiAnnoncesDeLogements.result.map((strapiAnnonceDeLogement) => strapiAnnonceDeLogement.slug);
il manque des try catch sur les mappers (cf décisions jardinage tech ?)

2024-01-04 09:01 UTC, juliebrunetto83 commented on package-lock.json
coucou toi que fais tu ici ?

2024-01-04 09:05 UTC, juliebrunetto83 commented on src/server/cms/domain/annonceDeLogement.type.ts
>  export interface AnnonceDeLogementIndexee extends BaseHit {
à deplacer ?

2024-01-04 09:07 UTC, juliebrunetto83 commented on src/server/cms/infra/repositories/strapi.response.ts
>  		export namespace AnnonceLogement {
encore un annonceLogement dans le cms ?

2024-01-04 09:13 UTC, juliebrunetto83 commented on src/server/logements/infra/strapiAnnonceDeLogement.repository.test.ts
> +				expect((result as Success<AnnonceDeLogement>).result).toEqual(anAnnonceDeLogement());
tu as besoin du `as` ici ? comme tu test que c'est un succès au dessus ?

2024-01-04 09:14 UTC, juliebrunetto83 commented on src/server/logements/infra/strapiAnnonceDeLogement.repository.test.ts
> +				it('relaye l’erreur du service de gestion d’erreur', async () => {
relaie* (je crois)

2024-01-04 09:26 UTC, juliebrunetto83 requested changes
en attente de l'homogénéisation + retours

2024-01-04 09:36 UTC, suli-octo commented on src/server/cms/domain/annonceDeLogement.type.ts
>  export interface AnnonceDeLogementIndexee extends BaseHit {
à côté de feature annonce de logement me paraît + logique, WDYT ?

2024-01-04 09:37 UTC, suli-octo commented on src/server/cms/infra/repositories/strapi.response.ts
>  		export namespace AnnonceLogement {
Ah je me disais bien que j'arrivais pas à le retrouver alors que c'était dans ma todo, merci :D

2024-01-04 09:39 UTC, suli-octo commented on src/server/logements/infra/strapiAnnonceDeLogement.repository.test.ts
> +				expect((result as Success<AnnonceDeLogement>).result).toEqual(anAnnonceDeLogement());
oui, expect de jest n'interfère pas avec le typage typescript, si ça avait été un if(isSuccess(result)) typescript casterait automatiquement

2024-01-04 09:40 UTC, juliebrunetto83 commented on src/server/cms/domain/annonceDeLogement.type.ts
>  export interface AnnonceDeLogementIndexee extends BaseHit {
oui

2024-01-04 10:00 UTC, juliebrunetto83 approved these changes

2024-01-04 10:05 UTC, merged