fix: fix redimensionnement iframe 1jeune1permis
DNUM-SocialGouv/1j1s-front pull request #2441
Opened 2023-12-11 17:01 UTC by gmoocto

2023-12-12 08:37 UTC, gmoocto commented on src/pages/1jeune1permis/index.page.tsx
> +	}, 100);
meta: on leur a demandé si c'était possible de plutôt nous envoyer l'evenement à chaque redimensionnement -> Dans l'attente de la réponse, on met en place cette solution pas hyper élégante mais qui fait le taf

2023-12-14 09:42 UTC, Mintoo200 requested changes

2023-12-14 09:42 UTC, Mintoo200 commented on src/pages/1jeune1permis/index.page.tsx
> +		if (data.type === 'resize-iframe') {
On n'a pas besoin de ce `if` si ? (Vu que si c'est pas `resize-iframe` ça early return dans le if au dessus)

2023-12-14 09:42 UTC, Mintoo200 commented on src/pages/1jeune1permis/index.page.tsx
> +			data = JSON.parse(event.data) as MessageEventData;
Vu que data est déjà typé, on n'a pas besoin de caster si ?

2023-12-14 09:42 UTC, Mintoo200 commented on src/pages/1jeune1permis/index.page.tsx
> +		if (event.origin !== DOMAINE_1JEUNE_1PERMIS || typeof data !== 'object' || data.type !== 'resize-iframe') {
J'aurais bien fait remonter le check de l'origine avant de parser (tant pis pour les 2 `if`, ça rend pas ça moins lisible je pense)

2023-12-14 09:42 UTC, Mintoo200 commented on src/pages/1jeune1permis/index.page.tsx
> +					height={iframeHeight}
> Vérifier l’absence des attributs de présentation : [...], height (exception faite des éléments `<img>`, `<object>`, `<embed>`, `<canvas>` et `<svg>`) ;

— [RGAA – Test 10.1.2](https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/#10.1.2)

😬 

Une autre solution serait de passer par une _custom property_ : 
```tsx
<iframe className={styles.iframe}
	title="Informations sur le dispositif 1 jeune 1 permis"
	src={URL_IFRAME_1JEUNE_1PERMIS}
	style={{ "--height" : height } as React.CSSProperties}>
```
```css
iframe {
  height: var(--height, 1600px)
}
```
(Ça a l'air de faire ce qu'il faut quand `height` est undefined et prendre la valeur par défaut de 1600px)

2023-12-14 09:42 UTC, Mintoo200 commented on src/pages/1jeune1permis/index.page.tsx
> +	const iRef = useRef<HTMLIFrameElement>(null);
![image](https://github.com/DNUM-SocialGouv/1j1s-front/assets/25901730/797acd6e-77c2-4fb7-8de5-8d2b9fa62815)

2023-12-14 09:45 UTC, Mintoo200 commented on src/pages/1jeune1permis/index.page.tsx
> +					height={iframeHeight}
Ça veut aussi dire qu'on a pas une `height` à deux endroit et du coup pas besoin de savoir que celui en attribut prend la précédence sur celui dans le CSS

2023-12-14 10:17 UTC, Mintoo200 commented on src/pages/1jeune1permis/index.page.tsx
> +		(iRef.current?.contentWindow)?.postMessage('size-request', '*');
```suggestion
		iRef.current?.contentWindow?.postMessage('size-request', '*');
```

2023-12-14 10:21 UTC, gmoocto commented on src/pages/1jeune1permis/index.page.tsx
> +			data = JSON.parse(event.data) as MessageEventData;
Ah oui ! Je pensais que `JSON.parse` renvoyait du `unknown` mais ça renvoie `any` donc on peut se passer du cast

2023-12-14 14:03 UTC, gmoocto commented on src/pages/1jeune1permis/index.page.tsx
> +	const iRef = useRef<HTMLIFrameElement>(null);
C'est une révolution !

2023-12-18 10:49 UTC, Mintoo200 approved these changes

2023-12-18 10:49 UTC, Mintoo200 commented on src/pages/1jeune1permis/index.module.scss
> +  height: var(--1jeune1permis-iframe-height);
On a une garantie que ça ne sera jamais plus petit que 1600px ? Je me demande s'il ne vaudrait pas mieux avoir 1600px comme valeur par défaut mais laisser le resize avoir le dernier mot 🤔

2023-12-18 10:49 UTC, Mintoo200 commented on src/pages/1jeune1permis/index.page.test.tsx
> +		expect(iframe).toHaveAttribute('style', '--1jeune1permis-iframe-height: 2000px;');
Tu peux aussi faire avec `toHaveStyle()`, mais tu garde l'indirection de la _custom property_ malheureusement : 
```suggestion
		expect(iframe).toHaveStyle({
			'--1jeune1permis-iframe-height': '2000px',
		});
```
voire
```suggestion
		expect(iframe).toHaveStyle({
			'--1jeune1permis-iframe-height': '2000px',
			height: 'var(--1jeune1permis-iframe-height)',
		});
```
Je ne sais pas si c'est mieux, je te laisse décider 🤔 

**Edit**: Je n'ai pas trouvé de version équivalente au `not.toHaveAttribute('style')` avec `toHaveStyle()` qui ne rendait pas le code incompréhensible. Aucun des suivants ne fonctionne correctement : 
```js
expect(iframe).toHaveStyle(expect.not.objectContaining('--1jeune1permis-iframe-height'));
expect(iframe).not.toHaveStyle(expect.objectContaining('--1jeune1permis-iframe-height'));
expect(iframe).toHaveStyle(expect.not.stringContaining('--1jeune1permis-iframe-height'));
expect(iframe).not.toHaveStyle(expect.stringContaining('--1jeune1permis-iframe-height'));
expect(iframe).not.toHaveStyle({ '--1jeune1permis-iframe-height': expect.anything() });
```
Ça semble dût au fait que `toHaveStyle()` doit convertir en string et que par conséquent, soit il fail pour les 4 premiers, soit il check contre la string "--1jeune1permis-iframe-height: Anything" (qui du coup est toujours vrai) pour le dernier

2023-12-18 18:33 UTC, merged