Feat/411 brancher fiches metiers meilisearch
DNUM-SocialGouv/1j1s-front pull request #245
Opened 2022-08-30 14:21 UTC by paulgallocto

2022-08-31 09:04 UTC, olivocto commented on src/pages/decouvrir-les-metiers/index.tsx
> +        <AngleRightIcon className={styles.cardLinkIcon}/>
il y a un composant générique Icon qui prend en paramètre le nom de l'icone

2022-08-31 09:10 UTC, olivocto commented on src/server/fiche-metier/infra/repositories/ficheMetierMeilisearch.repository.ts
> +	  return createSuccess(mapFichesMetierResult(result));
la gestion des erreurs est manquante

2022-08-31 09:14 UTC, olivocto commented on src/server/fiche-metier/infra/repositories/ficheMetierMeilisearch.repository.ts
> +    if (page && numberOfResult) offset = (page - 1) * numberOfResult;
est-ce vraiment nécessaire vu que tu assignes des valeurs par défaut à page et numberOfResult ? Ca devrait toujours être vrai

2022-08-31 09:16 UTC, olivocto commented on src/server/fiche-metier/infra/repositories/ficheMetierMeilisearch.repository.ts
> +    const result: SearchResponse<FicheMétierHttp> = await this.client.index('fiche-metier').search(
il me semble que le bon typage serait plutôt SearchResponse<Partial<FicheMétierHttp>>
à modifier également dans le mapper mapFichesMetierResult

2022-08-31 09:22 UTC, olivocto commented on src/pages/api/fiche-metier/index.ts
> +  if (resultat.instance === 'success') {
depuis fin juillet Théo à ajouté une gestion des réponse mutualisée, tu peux utiliser handleResponse ici

2022-08-31 09:24 UTC, olivocto commented on src/pages/decouvrir-les-metiers/decouvrir-les-metiers.module.scss
> +  background-color: white;
il y a une variable pour la couleur, $color-surface je crois

2022-08-31 09:24 UTC, olivocto commented on src/pages/decouvrir-les-metiers/decouvrir-les-metiers.module.scss
> +    font-weight: bold;
il y a un placeholder qui existe pour la font-weight

2022-08-31 09:25 UTC, olivocto commented on src/pages/decouvrir-les-metiers/decouvrir-les-metiers.module.scss
> +  background-color: white;
$color-surface

2022-08-31 09:30 UTC, olivocto commented on src/pages/decouvrir-les-metiers/decouvrir-les-metiers.module.scss
> +  width: 16px;
en rem pour le zoom 200 ce sera mieux

2022-08-31 09:33 UTC, AliElAmrani commented on src/pages/decouvrir-les-metiers/decouvrir-les-metiers.module.scss
> +  background-color: white;
ou bien $color-background vu que c'est un background

2022-08-31 09:33 UTC, olivocto commented on src/pages/decouvrir-les-metiers/decouvrir-les-metiers.module.scss
> +  width: 16px;
en réalité tu ne devrais pas avoir besoin de cette classe. Il existe un placeholder utlisable: @extend %linkWithRightIcon;. Je t'invite à regarder comment a été fait en savoir plus > par exemple dans RésultatRechercherSolution

2022-08-31 09:35 UTC, AliElAmrani commented on src/server/fiche-metier/infra/repositories/ficheMetierMeilisearch.repository.ts
> +  };
l'indent est normal ?

2022-08-31 09:38 UTC, olivocto commented on src/pages/decouvrir-les-metiers/index.tsx
> +              icon={<MagnifyingGlassIcon className={styles.submitButtonIcon} />}
pas besoin de cette classe, la taille de l'icone est déjà géré automatiquement en rem

2022-08-31 09:42 UTC, olivocto commented on src/pages/decouvrir-les-metiers/index.tsx
> +        <Container className={styles.formContainer}>
soucis de style pour le zoom 200,
sur la page emplois le bouton est bien à la ligne par exemple, tu pourrais t'inspirer du css
<img width="547" alt="image" src="https://user-images.githubusercontent.com/102825843/187649342-24bdce9e-604a-4deb-8abd-07919662d0a9.png">

2022-08-31 09:55 UTC, AliElAmrani commented on src/pages/decouvrir-les-metiers/index.tsx
> +import { useRouter } from 'next/router';
Il manque un moyen d'accéder à la page via le header

2022-08-31 09:56 UTC, olivocto requested changes

2022-08-31 09:56 UTC, olivocto commented on tests/pages/decouvrir-les-metiers/index.test.tsx
> +/**
il va te manquer les tests sur le repository et sur ton apiHandler également

2022-08-31 12:20 UTC, paulgallocto commented on src/server/fiche-metier/infra/repositories/ficheMetierMeilisearch.repository.ts
> +    if (page && numberOfResult) offset = (page - 1) * numberOfResult;
oui car le linter ne semble pas prendre en compte qu'il y a une valeur par défaut.. Donc il me met une erreur

2022-09-01 08:48 UTC, olivocto commented on src/pages/decouvrir-les-metiers/index.tsx
> +        <AngleRightIcon className={styles.cardLinkIcon}/>
`<span className={styles.callToAction}>
       En savoir plus
        <Icon name="angle-right" />
    </span>
`
avec callToAction: 
`.callToAction {
  @extend %linkWithRightIcon;
}
`

2022-09-01 08:49 UTC, olivocto approved these changes

2022-09-01 08:50 UTC, merged