ci: do not run test&lint on specific branches
DNUM-SocialGouv/1j1s-front pull request #2486
Opened 2023-12-20 13:39 UTC by gmoocto

2023-12-20 14:23 UTC, josephpage requested changes

2023-12-20 14:23 UTC, josephpage commented on .github/workflows/run-lint-and-unit-test.yml
> +    if: ${{ ! github.event.sender.name == 128365508 }}
Il faudrait documenter à quoi correspond `128365508`
et le titre de la PR ne semble pas avoir de lien avec le commit, à moins que je me trompe

2023-12-20 14:48 UTC, gmoocto commented on .github/workflows/run-lint-and-unit-test.yml
> +    if: ${{ ! github.event.sender.name == 128365508 }}
Oui, on était en plein tests :D  (je bascule en draft)

2024-03-13 13:58 UTC, suli-octo commented
aborted Cf décisions jardi tech

2024-03-13 13:58 UTC, closed without merging