feat(CEJ): ajout de la gestion d'erreur sur les formulaires accompagnement
DNUM-SocialGouv/1j1s-front pull request #2530
Opened 2024-01-05 14:53 UTC by juliebrunetto83

2024-01-05 14:58 UTC, juliebrunetto83 commented on src/client/components/features/ContratEngagementJeune/Accompagnement/Modales/ModaleMissionLocale.tsx
> +// TODO (BRUJ 05/01/2024): modifier pour utiliset setIsOpen
enlever le com

2024-01-05 14:59 UTC, juliebrunetto83 commented on src/client/components/features/ContratEngagementJeune/DemandeDeContactCEJ/DemandeContactCEJ.tsx
> +import { Container } from '../../../layouts/Container/Container';
import relatif

2024-01-05 14:59 UTC, juliebrunetto83 commented on src/client/components/features/ContratEngagementJeune/DemandeDeContactCEJ/ModaleDemandeContactCEJ/ModaleDemandeContactCEJ.tsx
> +// TODO (BRUJ 05/01/2024): supprimer le style de success
supprimer le com (ça a été fait)

2024-01-08 14:33 UTC, gmoocto commented on src/client/components/features/Accompagnement/DemandeDeContact/ModalDemandeDeContactAccompagnement.tsx
> +				setIsOpen(true);
C'est surprenant ça? 
Le `onClose` s'applique quand on clique sur la croix en haut à droite aussi non? 
Ça fait pas bizzare de devoir cliquer deux fois dessus pour fermer la modale "pour de vrai" ?

2024-01-08 14:34 UTC, gmoocto commented on src/client/components/features/Accompagnement/DemandeDeContact/ModalDemandeDeContactAccompagnement.tsx
> +						}}
Proposition : 
deux méthodes `onSuccess` et `onFailure`
(je trouve ça un peu plus facile à lire)

2024-01-08 15:07 UTC, gmoocto commented on src/client/components/features/ContratEngagementJeune/DemandeDeContactCEJ/DemandeContactCEJ.test.tsx
> +				await act(() => delay(300));
On pourrait mettre le 300 dans une constante exportée par la modale

2024-01-08 15:11 UTC, gmoocto commented on src/client/components/features/ContratEngagementJeune/FormulaireContactCEJ/FormulaireContactCEJ.tsx
> +	isSuccessOnSubmit: (isSuccess: boolean) => void;
Idem ici, je suggérerais deux méthodes : onSuccess et onFailure

2024-01-08 15:11 UTC, gmoocto requested changes
.

2024-01-09 08:13 UTC, juliebrunetto83 commented on src/client/components/features/Accompagnement/DemandeDeContact/ModalDemandeDeContactAccompagnement.tsx
> +				setIsOpen(true);
si ton formulaire est en erreur tu as envie de relancer la demande j'imagine ? j'ai suivi le ticket pour le bouton de retour au formulaire mais à confirmer si c'est la même chose que quand tu cliques sur la croix

2024-01-09 08:14 UTC, juliebrunetto83 commented on src/client/components/features/Accompagnement/DemandeDeContact/ModalDemandeDeContactAccompagnement.tsx
> +						}}
d'accord j'avoue que les deux me vont

2024-01-09 08:14 UTC, juliebrunetto83 commented on src/client/components/features/ContratEngagementJeune/DemandeDeContactCEJ/DemandeContactCEJ.test.tsx
> +				await act(() => delay(300));
yes

2024-01-10 09:47 UTC, juliebrunetto83 commented on src/client/components/features/Accompagnement/DemandeDeContact/ModalDemandeDeContactAccompagnement.tsx
> +				setIsOpen(true);
J'ai rajouté onBackToForm vs OnClose 

Tu en penses quoi ?

2024-01-10 10:34 UTC, gmoocto approved these changes

2024-01-10 13:36 UTC, merged