feat(UI): mise en place d'un select accessible etape 1
DNUM-SocialGouv/1j1s-front pull request #3027
Opened 2024-05-28 07:03 UTC by juliebrunetto83

2024-05-30 14:08 UTC, Mintoo200 requested changes

2024-05-30 14:15 UTC, juliebrunetto83 commented on src/client/components/features/OffreEmploi/FormulaireRecherche/FormulaireRechercheOffreEmploi.test.tsx
> +import CONTRAT_CDD = Offre.CONTRAT_CDD;
ça évite d'utiliser Offre.CONTRAT_CDD, mon IDE qui m'auto importe les éléments n'importe comment

2024-05-30 14:15 UTC, juliebrunetto83 commented on src/client/components/ui/Form/Select/Select.module.scss
seconde PR

2024-05-30 14:20 UTC, juliebrunetto83 commented on src/client/components/ui/Form/Select/Select.tsx
> +				event.preventDefault();
A prendre dans une PR à part

2024-05-30 14:22 UTC, juliebrunetto83 commented on src/client/components/features/Accompagnement/DemandeDeContact/Formulaire/FormulaireDemandeDeContactAccompagnement.test.tsx
> +		expect(combobox).toHaveAccessibleDescription(/Séléctionnez un élément de la liste/);
PR à part

2024-05-30 16:30 UTC, Mintoo200 commented on src/client/components/ui/Form/Select/Select.test.tsx
> +					}, { libellé: 'options 3', valeur: '3' }];
```suggestion
					const options = [
						{ libellé: 'options 1', valeur: '1' },
						{ libellé: 'options 2', valeur: '2' },
						{ libellé: 'options 3', valeur: '3' }
					];
```

2024-05-30 16:30 UTC, Mintoo200 commented on src/client/components/ui/Form/Select/Select.test.tsx
> +					const option1Id = screen.getByRole('option', { name: 'options 1' }).id;
Ces deux tests testent indirectement que la liste s'ouvre (de par le fait que tu arrive à récupérer l'option), mais si ça fait partie du nom du test, je pense que j'aimerais mieux l'avoir explicitement avec `toBeVisible()`

2024-05-30 16:30 UTC, Mintoo200 commented on src/client/components/ui/Form/Select/Select.test.tsx
> +				it('lorsque l‘utilisateur fait "Tab", l‘option qui a le focus visuel est séléctionné, la liste d‘option se ferme, le placeholder se met ç jour et le focus se déplace sur le prochain élément focus
```suggestion
				it('lorsque l‘utilisateur fait "Tab", l‘option qui a le focus visuel est séléctionné, la liste d‘option se ferme, le placeholder se met à jour et le focus se déplace sur le prochain élément focusable', async () => {
```

2024-05-30 16:30 UTC, Mintoo200 commented on src/client/components/ui/Form/Select/Select.test.tsx
> +			it('lorsqu‘un placeholder est donné en props', () => {
```suggestion
			it('affiche le placeholder lorsqu‘un placeholder est donné en props', () => {
```

2024-05-30 16:30 UTC, Mintoo200 commented on src/client/components/ui/Form/Select/Select.test.tsx
> +				}));
```suggestion
				const option = screen.getByRole('option', { name: /options 2/i });
				await user.click(option);

				expect(onChange).toHaveBeenCalledWith(option);
```

2024-05-30 16:30 UTC, Mintoo200 commented on src/client/components/ui/Form/Select/Select.test.tsx
> +			it('lorsque le champ est requis mais pas touché, je ne vois le message d‘erreur', () => {
```suggestion
			it('lorsque le champ est requis mais pas touché, je ne vois pas le message d‘erreur', () => {
```

2024-05-30 16:30 UTC, Mintoo200 commented on src/client/components/ui/Form/Select/Select.test.tsx
> +				expect(screen.queryByText('Séléctionnez un élément de la liste')).not.toBeInTheDocument();
```suggestion
				render(<>
					<Select optionList={options} label={'label'} required/>
				</>);

				await user.tab();
				await user.keyboard(KeyBoard.ENTER);
				await user.keyboard(KeyBoard.ESCAPE);

				await user.keyboard(KeyBoard.ENTER);
				await user.keyboard(KeyBoard.ARROW_DOWN);
				await user.keyboard(KeyBoard.ENTER);

				expect(screen.getByRole('combobox')).toHaveAccessibleDescription('');
				expect(screen.queryByText('Séléctionnez un élément de la liste')).not.toBeInTheDocument();
```

2024-05-31 13:56 UTC, Mintoo200 approved these changes

2024-06-03 07:42 UTC, merged