feat(a11y): nom accessible pour lien Stage de 2de
DNUM-SocialGouv/1j1s-front pull request #3113
Opened 2024-06-26 08:37 UTC by sylviamoreno

2024-06-26 09:16 UTC, juliebrunetto83 commented on src/client/components/layouts/Header/Navigation/NavigationStructure.tsx
> +			label: <>Stage de 2de GT <Icon className={styles.externalIcon} name="external-redirection" aria-label="Nouvel onglet" /></>,
j'aurais plutôt modifié dans le NavItem pour que si j'ai une redirection externe j'ajoute un link.icon car c'est une règle générique si on a un lien de redirection externe on souhaite avoir l'icon informative

et si tu mets un Link.Icon dans le NavItem tu n'auras plus besoin de mettre d'aria-label

2024-06-26 09:16 UTC, juliebrunetto83 requested changes
On peut en rediscuter si besoin

2024-06-26 09:46 UTC, sylviamoreno commented on src/client/components/layouts/Header/Navigation/NavigationStructure.tsx
> +			label: <>Stage de 2de GT <Icon className={styles.externalIcon} name="external-redirection" aria-label="Nouvel onglet" /></>,
ah oui effectivement bonne idée, je corrige ça 👍

2024-06-28 07:39 UTC, juliebrunetto83 approved these changes

2024-06-28 09:42 UTC, Mintoo200 approved these changes

2024-06-28 09:42 UTC, Mintoo200 commented on src/client/components/layouts/Header/Navigation/Nav.module.scss
> +    }
Pourquoi on a besoin du ::before ? C'est pour avoir toute la zone cliquable mais garder l'alignement à gauche ? Ça me parait overkill, on peut pas juste soit virer le `justify-content: center` soit l'override ?

2024-06-28 09:42 UTC, Mintoo200 commented on src/client/components/layouts/Header/Navigation/Nav.module.scss
> +      height: 1.1rem;
C'est étonnant ça, on aurait pas un problème d'unité sur le `Link.Icon` ? On ne pourrait pas juste le faire avec des `em` pour que ça s'adapte à la taille de police de là où c'est utilisé ?

2024-06-28 09:42 UTC, Mintoo200 commented on src/client/components/ui/Link/Link.tsx
> +}
❤️

2024-06-28 09:42 UTC, Mintoo200 commented on src/client/components/ui/Link/Link.tsx
> +function DefaultLinkIcon({ className }: DefaultLinkIconProps) {
Par contre, ici, tu ne fait pas passer le reste des props de `Icon`

2024-06-28 13:52 UTC, merged