feat/UNJ1S-2130: fermer le menu hors focus
DNUM-SocialGouv/1j1s-front pull request #3133
Opened 2024-07-02 10:36 UTC by sylviamoreno

2024-07-03 09:13 UTC, juliebrunetto83 commented on src/client/components/layouts/Header/Navigation/NavItemWithSubItems.test.tsx
> +			fireEvent.click(menuButton);
on utilise plutot await userEvent.click ... sur le projet

2024-07-03 09:13 UTC, juliebrunetto83 commented on src/client/components/layouts/Header/Navigation/NavItemWithSubItems.test.tsx
> +		expect(screen.getByRole('button', { name: 'Test Menu' })).toBeInTheDocument();
toBeVisible()

2024-07-03 09:15 UTC, juliebrunetto83 commented on src/client/components/layouts/Header/Navigation/NavItemWithSubItems.test.tsx
> +			expect(screen.getByText('Sub Item 1')).toBeInTheDocument();
tu pourrais utiliser un `` getByRole('listitem', { name: 'Sub Item 1'}) `` je pense

2024-07-03 09:16 UTC, juliebrunetto83 commented on src/client/components/layouts/Header/Navigation/NavItemWithSubItems.test.tsx
> +			fireEvent.click(menuButton);
je te laisse changer les autres occurrences aussi

2024-07-03 09:17 UTC, juliebrunetto83 commented on src/client/components/layouts/Header/Navigation/NavItemWithSubItems.test.tsx
> +			expect(screen.getByText('Sub Item 1')).toBeInTheDocument();
pareil sur les autres éléments

2024-07-03 09:17 UTC, juliebrunetto83 commented on src/client/components/layouts/Header/Navigation/NavItemWithSubItems.test.tsx
> +		it('doit afficher l‘attribut aria-expanded attribute correctement', () => {
'attribute' en trop ?

2024-07-03 09:17 UTC, juliebrunetto83 commented on src/client/components/layouts/Header/Navigation/NavItemWithSubItems.test.tsx
> +		it('doit afficher l‘attribut aria-expanded attribute correctement', () => {
test du dessous aussi ?

2024-07-03 09:19 UTC, juliebrunetto83 commented on src/client/components/layouts/Header/Navigation/NavItemWithSubItems.test.tsx
> +		it('doit afficher l‘attribut aria-current attribute à false', () => {
lorsque la page n‘est pas la page visité, doit afficher l‘attribut aria-current à false 

et du coup il manquerait aussi l'autre test quand il est à true

2024-07-03 09:28 UTC, juliebrunetto83 commented on src/client/components/layouts/Header/Navigation/NavItemWithSubItems.tsx
>  		document.addEventListener('keyup', closeMenuOnEscape);
je pense que tu peux utiliser directement le onBlur 

Sur le combobox tu devrais voir un exemple d'implem

2024-07-03 09:33 UTC, juliebrunetto83 commented on src/client/components/layouts/Header/Navigation/NavItemWithSubItems.tsx
tu peux utiliser le onBlur plutot
Tu peux t'inspirer du combobox je pense

2024-07-03 09:33 UTC, juliebrunetto83 requested changes
trop bien l'ajout des tests !

2024-07-03 09:35 UTC, juliebrunetto83 commented on src/client/components/layouts/Header/Navigation/NavItemWithSubItems.test.tsx
> +/**
avec la navigation au clavier

2024-07-09 12:26 UTC, juliebrunetto83 commented on src/client/components/layouts/Header/Navigation/NavDesktopEmployeur.test.tsx
> +		mockUseRouter.mockReturnValue({
mockUseRouter({});

2024-07-09 12:27 UTC, juliebrunetto83 commented on src/client/components/layouts/Header/Navigation/NavDesktopEmployeur.test.tsx
> +		render(<NavDesktopEmployeur item={mockItem} />);
const user = userEvent.setup()

....

await user.click(..)

2024-07-09 12:28 UTC, juliebrunetto83 commented on src/client/components/layouts/Header/Navigation/NavDesktopEmployeur.test.tsx
> +		expect(screen.getByRole('link', { name: 'Sous-section 1' })).toBeInTheDocument();
toBeVisible()

2024-07-09 12:31 UTC, juliebrunetto83 commented on src/client/components/layouts/Header/Navigation/NavItemWithSubItems.test.tsx
> +				mockUseRouter({ pathname: '/sub1' });
tu as besoin de ce beforeEach ?

2024-07-09 12:31 UTC, juliebrunetto83 commented on src/client/components/layouts/Header/Navigation/NavItemWithSubItems.test.tsx
> +		beforeEach(() => {
pareil ici

2024-07-09 12:32 UTC, juliebrunetto83 commented on src/client/components/layouts/Header/Navigation/NavItemWithSubItems.test.tsx
> +			rerender(<NavItemWithSubItems navigationItemWithChildren={mockNavigationItemWithChildren} />);
tu as besoin de rerender ?

2024-07-09 12:32 UTC, juliebrunetto83 commented on src/client/components/layouts/Header/Navigation/NavItemWithSubItems.test.tsx
> +		beforeEach(() => {
beforeEach ?

2024-07-09 12:33 UTC, juliebrunetto83 commented on src/client/components/layouts/Header/Navigation/NavItemWithSubItems.test.tsx
> +		beforeEach(() => {
Ah non ici c'est ok !

2024-07-09 12:35 UTC, juliebrunetto83 commented on src/client/components/layouts/Header/Navigation/NavItemWithSubItems.test.tsx
> +			await user.keyboard(`{${KeyBoard.ESCAPE}}`);
c'est juste pas le bon import

2024-07-09 12:40 UTC, juliebrunetto83 commented on src/client/components/layouts/Header/Navigation/NavItemWithSubItems.test.tsx
> +		describe('lorsqu‘un élément du sous-menu est cliqué', () => {
On pourrait se passer du describe ici, vu qu'on a qu'un seul it 

it('lorsqu‘un élément du sous-menu est cliqué, appelle la props onClick une fois' ...

2024-07-09 12:44 UTC, juliebrunetto83 commented on src/client/components/layouts/Header/Navigation/NavItemWithSubItems.test.tsx
> +			fireEvent.mouseUp(screen.getByTestId('outside'));
await user.click(screen.getByTestId('outside'))

2024-07-09 13:07 UTC, sylviamoreno commented on src/client/components/layouts/Header/Navigation/NavItemWithSubItems.test.tsx
> +			fireEvent.mouseUp(screen.getByTestId('outside'));
ok corrigé

2024-07-09 13:52 UTC, juliebrunetto83 approved these changes

2024-07-09 13:57 UTC, sylviamoreno commented on src/client/components/layouts/Header/Navigation/NavItemWithSubItems.test.tsx
> +			await user.keyboard(`{${KeyBoard.ESCAPE}}`);
j'ai testé avec la fixture ça ne passe pas... en regardant les autres tests c'est l'enum que l'on utilise

2024-07-09 14:47 UTC, merged