feat(LinkCard & ServiceCard):  correction clic sur la carte
DNUM-SocialGouv/1j1s-front pull request #3329
Opened 2024-09-16 22:45 UTC by sylviamoreno

2024-09-18 15:17 UTC, Mintoo200 commented on src/client/components/ui/Card/Link/LinkCard.module.scss
> +    max-height: 150px;
Un jour faudrait qu'on jette un coup d'œil un peu plus dans le détail sur ces fichiers, parce qu'il y a de ces dingueries

2024-09-18 15:19 UTC, Mintoo200 commented on src/client/components/ui/Card/Link/LinkCard.module.scss
> +        background-color: rgba(0, 0, 0, 0);
Samesies

2024-09-18 15:24 UTC, Mintoo200 commented on src/client/components/ui/Card/Link/LinkCard.tsx
> +	function LinkCardTitle({ children, className, id }: { titleAs?: HtmlHeadingTag, id: string } & React.HTMLAttributes<HTMLTitleElement>) {
```suggestion
	function LinkCardTitle({ children, className, id }: { titleAs?: HtmlHeadingTag, id: string } & React.HTMLAttributes<HTMLHeadingElement>) {
```
Parce que sinon, c'est pour la balise `title`. Et du coup, t'as pas besoin de spécifier l'`id` ou le `className` puisque ça fait partie des props d'un `hx` donc
```suggestion
	function LinkCardTitle({ children }: { titleAs?: HtmlHeadingTag } & React.HTMLAttributes<HTMLHeadingElement>) {
```

2024-09-18 15:32 UTC, Mintoo200 commented on src/client/components/ui/Card/Link/LinkCard.tsx
> +					<LinkCardTitle id={idLink} className={styles.cardTitle}>{title}</LinkCardTitle>
```suggestion
					<LinkCardTitle id={idIntitule} className={styles.cardTitle}>{title}</LinkCardTitle>
```

2024-09-18 15:34 UTC, Mintoo200 commented on src/client/components/ui/Card/Link/LinkCard.tsx
> +						</Link>
C'est le lien qui devrait prendre le label, pas l'icône.
```suggestion
						<Link aria-labelledby={`${idIntitule}, ${idLink}`} id={idLink} href={link} className={classNames('underline-none')} prefetch={false}>
							<Link.Icon name='angle-right' aria-hidden="false" />
						</Link>
```
Also, la partie textuelle du lien en `sr-only` devrait faire partie du lien

2024-09-24 15:36 UTC, sylviamoreno commented on src/client/components/features/ServiceCard/Card/ServiceCard.tsx
> +	const linkTitle = !isInternalLink ? `${linkLabel} - nouvelle fenêtre` : 'En savoir plus';
oui effectivement... je repasse sur la version précédente

2024-09-25 07:16 UTC, sylviamoreno commented
retours corrigés + tests @Mintoo200 si tu veux jeter un dernier coup d'oeil....

2024-09-30 09:32 UTC, Mintoo200 requested changes

2024-09-30 09:32 UTC, Mintoo200 commented on src/client/components/features/FormationAlternance/Consulter/Statistiques/StatistiquesFormationAlternance.test.tsx
> +			expect(article).toHaveTextContent('Lire l\'article');
Mais du coup le test ne test plus la card InserJeunes, juste qu'il y ait un lien "lire l'article"

2024-09-30 09:32 UTC, Mintoo200 commented on src/client/components/features/ServiceCard/Card/ServiceCard.tsx
> +	const linkTitle = !isInternalLink ? `${linkLabel} - nouvelle fenêtre` : 'En savoir plus';
Mais du coup c'est toujours pas bon là, si ?

2024-09-30 09:32 UTC, Mintoo200 commented on src/client/components/features/ServiceCard/Card/ServiceCard.tsx
>  					</span>
à priori, plus besoin d'un FakeLink, si maintenant on a un vrai link ?

2024-09-30 09:32 UTC, Mintoo200 commented on src/client/components/ui/Card/Link/LinkCard.tsx
> +	function LinkCardTitle({ children, className, id }: { titleAs?: HtmlHeadingTag, id: string } & React.HTMLAttributes<HTMLHeadingElement>) {
À moins que tu ne veuille rendre la props id obligatoire, pas besoin de la re-préciser, elle est déjà dans HTMLHeadingElement

2024-09-30 09:32 UTC, Mintoo200 commented on src/client/components/ui/Card/Link/LinkCard.tsx
> +		return React.createElement(titleAs || 'h3', { className: className, id }, children);
Tu accepte tous les attributs d'un HTMLHeadingElement, mais elles ne sont jamais passées à l'élément

2024-10-02 12:54 UTC, sokl-octo commented on src/client/components/features/FormationAlternance/Consulter/Statistiques/StatistiquesFormationAlternance.test.tsx
> +			expect(article).toHaveTextContent('Lire l\'article');
Les tests ne couvraient pas la card mais juste le titre du lien dans la carte

2024-10-02 13:20 UTC, sokl-octo commented on src/client/components/ui/Card/Link/LinkCard.tsx
> +	function LinkCardTitle({ children, className, id }: { titleAs?: HtmlHeadingTag, id: string } & React.HTMLAttributes<HTMLHeadingElement>) {
Il y a peut-être un problème avec l'implémentation du fix. Les getByRole du style ci-dessous ne trouvent plus le lien et font échouer les tests aux endroits :
`const link = screen.getByRole('link', { name: 'Aides financières au logement' });`

À la place le lien cherché a un nom accessible vide

2024-10-03 08:35 UTC, Mintoo200 commented on src/client/components/features/FormationAlternance/Consulter/Statistiques/StatistiquesFormationAlternance.test.tsx
> +			expect(article).toHaveTextContent('Lire l\'article');
Ben du coup le titre du test est pas bon ? `"affiche un article inserjeunes"`
Au passage, c'est pas super interessant de tester que le lien a le texte "Lire l'article", au moins tester le nom accessible qui devrait être plus explicite

2024-10-03 08:41 UTC, Mintoo200 commented on src/client/components/ui/Card/Link/LinkCard.tsx
> +	function LinkCardTitle({ children, className, id }: { titleAs?: HtmlHeadingTag, id: string } & React.HTMLAttributes<HTMLHeadingElement>) {
Ouais, en fait il n'y a rien qui va, il y a un `.sr-only` **en dehors du lien**, le lien a un `aria-labelledby` qui ne référence que le titre, qui, semble-t-il ne fonctionne pas ? En termes de code style, c'est le bordel, soit fait au mieux, soit on peut regarder ça demain

2024-10-07 10:26 UTC, Mintoo200 approved these changes

2024-10-09 09:18 UTC, merged