WIP(services-jeunes): exploration sélection champs avec étiquettes cliquables
DNUM-SocialGouv/1j1s-front pull request #3342
Opened 2024-09-25 13:41 UTC by sokl-octo

**Dépriorisé** : À faire après les développements de la campagne sur l'apprentissage

2024-11-05 11:48 UTC, Mintoo200 commented on src/pages/services-jeunes/index.page.test.tsx
> +
Tu peux t'inspirer de `mockUseRouter` pour intégrer ça directement dans une fonction `mockSearchParams` nan ?

2024-11-05 11:48 UTC, Mintoo200 commented on src/pages/services-jeunes/index.page.test.tsx
> +						const analyticsService = aManualAnalyticsService();
Si ça ne fait pas parti du setup important du test, je te propose de l'inliner pour le rendre plus discret

2024-11-05 11:48 UTC, Mintoo200 commented on src/pages/services-jeunes/index.page.test.tsx
> +						const servicesJeunesList = within(mesuresJeunesSection).getAllByRole('list')[1];
C'est un peu arbitraire le `getAllByRole()[1]`
```suggestion
						const [/* tags */, servicesJeunesList] = within(mesuresJeunesSection).getAllByRole('list');
```
Le commentaire autour de `tags`, c'est pour le linter, je crois qu'il n'est pas content avec la variable inutilisée sinon

2024-11-05 11:48 UTC, Mintoo200 commented on src/pages/services-jeunes/index.page.test.tsx
> +						const servicesJeunesList = within(mesuresJeunesSection).getAllByRole('list')[1];
Et avec le select dans le form, tu peux l'extraire en dehors de la section et du coup t'as plus qu'une liste

2024-11-05 11:48 UTC, Mintoo200 commented on src/pages/services-jeunes/index.page.test.tsx
> +						const servicesJeunesList = within(mesuresJeunesSection).getAllByRole('list')[0];
Du coup c'est pas la liste des services jeunes, c'est la liste des tags.
Mais du coup même recommandation que plus haut

2024-11-05 11:48 UTC, Mintoo200 commented on src/pages/services-jeunes/index.page.test.tsx
> +						const mesuresJeunesSection = screen.getByRole('region', { name: 'les services jeunes' });
Et en vrai, comme la section c'est en réalité toute la page, pas besoin ni de la section (elle représente dans ce cas la même chose que le main), et pas besoin de scoper tes `getByRole`

2024-11-05 11:48 UTC, Mintoo200 commented on src/pages/services-jeunes/index.page.test.tsx
> +						const servicesJeunesListBefore = within(mesuresJeunesSectionBefore).getAllByRole('list')[0];
Je suppose que le `...Before` c'est un reliquat de ce que tu avais testé avant de passer sur le `toHaveBeenCalled`

2024-11-05 11:48 UTC, Mintoo200 commented on src/pages/services-jeunes/index.page.test.tsx
> +							aServiceJeune({ categorie: ServiceJeune.Categorie.ACCOMPAGNEMENT, titre: 'service 1' }),
Si tu n'as pas besoin de faire d'assertion sur le titre, tu n'as normalement pas besoin de le préciser à chaque fois, tu peux laisser la valeur par défaut

2024-11-05 11:48 UTC, Mintoo200 commented on src/pages/services-jeunes/index.page.test.tsx
> +					];
```suggestion
					const serviceJeuneList = new Array(7).fill(aServiceJeune());
```
À tester, pas certain que ça fonctionne, mais comme ça c'est plus explicite que tu en met 7, c'est écrit en tout chiffre

2024-11-05 11:48 UTC, Mintoo200 commented on src/pages/services-jeunes/index.page.tsx
> +				return filtreList.filter((e) => e !== option.dataset.value!).map((e) => 'filtre=' + e).join('&');
T'as vraiment besoin du `!` ici ?

2024-11-05 11:48 UTC, Mintoo200 commented on src/pages/services-jeunes/index.page.tsx
> +	const toggleOption = useCallback(
Je pense que t'as moyen de pas mal simplifier la fonction en variabilisant en amont, quitte à ne pas utiliser la variable dans certains cas. E.g. : 
```ts
const value = option.dataset.value ?? option.textContent;
const selected = option.getAttribute('aria-selected');
if(filtreList.includes(value) && selected === 'true'){
        return filtreList.filter((filtre) => filtre !== value)
	        .map((filtre) => 'filtre=' + filtre)
	        .join('&');
//...
```

2024-11-05 11:48 UTC, Mintoo200 commented on src/pages/services-jeunes/index.page.tsx
> +	const toggleOption = useCallback(
Also, c'est probablement beaucoup plus simple de passer par un URLSearchParams à nouveau plutôt que de reconstruire à la main : 
1. Chopper l'ensemble des queryParams
2. Convertir en objet
3. Supprimer l'entrée à supprimer
4. Instancier un nouveau URLSearchParams avec ce nouvel objet
5. `URLSearchParams.toString()`
6. `router.push`

2024-11-05 11:48 UTC, Mintoo200 commented on src/pages/services-jeunes/index.page.tsx
> +	const toggleOption = useCallback(
D'autant que si l'utilisateur arrive avec ses propres queryParams (ou si on décide d'en ajouter nous), la version actuelle les supprime

2024-11-05 11:48 UTC, Mintoo200 commented on src/pages/services-jeunes/index.page.tsx
> +							Types de service à destination des jeunes
C'est Laurent qui t'as donné ce wording ? Ça parait beaucoup trop verbeux, on n'a pas besoin de préciser que c'est "à destination des jeunes", tout le site est à destination de jeunes

2024-11-05 11:48 UTC, Mintoo200 commented on src/pages/services-jeunes/index.page.tsx
> +								router.push(pathname + '?' + toggleOption(option));
🤔 Je me demande s'il n'y a pas moyen de faire hyper plus simple en trigger le submit du form dans le `onChange` et en laisse le form faire toute la gestion des queryParams de bout en bout

2024-11-05 11:48 UTC, Mintoo200 commented on src/pages/services-jeunes/index.page.tsx
> +								router.push(pathname + '?' + toggleOption(option));
C'est probablement pas une bonne idée, ça risque de refresh la page à chaque fois, mais je serais curieux de tester, voire checker s'il y a moyen avec l'event, de simplement récupérer les queryParams qui seraient ajoutés.

2024-11-05 11:48 UTC, Mintoo200 commented on src/pages/services-jeunes/index.page.tsx
> +								router.push(pathname + '?' + toggleOption(option));
Dans tous les cas, tu peux récupérer les FormData et instancier un URLSearchParams directement avec ces FormData

2024-11-05 11:48 UTC, Mintoo200 commented on src/pages/services-jeunes/index.page.tsx
> +							optionsAriaLabel={'Toto'}>
😬

2024-11-05 11:48 UTC, Mintoo200 commented on src/pages/services-jeunes/index.page.tsx
> +								<SelectMultiple.Option key={index} value={option}>{option}</SelectMultiple.Option>,
La value est optionnelle et pas nécessaire quand elle match le contenu textuel de l'option

2024-11-05 11:48 UTC, Mintoo200 commented on src/pages/services-jeunes/index.page.tsx
> +									{filtre}
C'est pas super explicite que cliquer dessus va supprimer le filtre, il faudrait ajouter un petit label je pense, ou une alternative directement sur l'icône, c'est probablement mieux même

2024-11-05 14:51 UTC, sokl-octo commented on src/pages/services-jeunes/index.page.tsx
> +									{filtre}
L'icône est svg, j'ai essayé d'ajouter un aria-label, mais au passage à la tabulation avec VoiceOver ça n'est pas restitué j'ai essayé de naviguer à l'intérieur du bouton même et pas de restit non plus. Du coup je pars sur un title sur button qui ajoute également une infobulle

2024-11-05 16:04 UTC, sokl-octo commented on src/pages/services-jeunes/index.module.scss
>  }
À mon retour j'encapsule dans le form

2024-11-05 16:05 UTC, sokl-octo commented on src/pages/services-jeunes/index.page.test.tsx
> +
C'est possible oui, je vois ça à mon retour après avoir réimplémenter une version avec URLSearchParams

2024-11-05 16:05 UTC, sokl-octo commented on src/pages/services-jeunes/index.page.tsx
> +	const toggleOption = useCallback(
Pour mon retour

2024-11-05 16:05 UTC, sokl-octo commented on src/pages/services-jeunes/index.page.tsx
> +								router.push(pathname + '?' + toggleOption(option));
Pour mon retour

2024-11-13 14:30 UTC, sokl-octo commented on src/pages/services-jeunes/index.page.tsx
> +								router.push(pathname + '?' + toggleOption(option));
Pour éviter de refresh il faut utiliser un `preventDefault`, mais pour utiliser cette méthode il faut que le formulaire ait été submit soit avec un bouton classique soit avec `requestSubmit` et non avec `submit` Citation du MDN :
> This method is similar, but not identical to, activating a form's submit button. When invoking this method directly, however: No submit event is raised. In particular, the form's onsubmit event handler is not run. Constraint validation is not triggered.

`requestSubmit`, elle, n'est supportée qu'à 93.7% (ajouté mi 2022 sur Safari Desktop et iOS). Je pense drop même si ça aurait été sympa. Je vais simplifier les méthodes seulement.

2024-11-13 14:34 UTC, sokl-octo commented on src/pages/services-jeunes/index.page.tsx
> +								router.push(pathname + '?' + toggleOption(option));
2e pb sur lequel je suis tombé c'est qu'un `new FormData(event.target)` ne choppait aucune entrée malgré les options cochées dans le formulaire.

2024-11-27 10:02 UTC, Mintoo200 requested changes

2024-11-27 14:17 UTC, sokl-octo commented on src/client/components/useRouter.mock.ts
> +	useRouter.mockImplementation(() => (routerMock));
Ça casse des tests 😬

2024-11-28 10:28 UTC, closed without merging