feat: filtres résultats par expérience domaine et  temps de travail
DNUM-SocialGouv/1j1s-front pull request #39
Opened 2022-05-24 13:28 UTC by olivocto

2022-05-25 15:59 UTC, Drastal commented on src/client/components/ui/Select/SelectComponent.tsx
> +export function SelectComponent(props: CustomSelectProps) {
J'ai trouvé un type dans React qui semble sympa pour les children : React.PropsWithChildren

2022-05-25 15:59 UTC, Drastal commented on src/client/components/ui/Select/SelectRadio/SelectRadio.tsx
> +          value={`${option.valeur}`}
Pas besoin du template string ici :D

2022-05-25 15:59 UTC, Drastal commented on src/client/components/ui/Select/SelectRadio/SelectRadio.tsx
> +          checked={currentInput.includes(`${option.valeur}`)}
Ici non plus 🙃

2022-05-25 15:59 UTC, Drastal commented on src/client/components/ui/Select/SelectRadio/SelectRadio.tsx
> +export function SelectRadio(props: SelectRadioProps) {
Il serait bien que ce composant soit appelable directement sans le composant Select. Idem pour la version Checbox

2022-05-25 15:59 UTC, Drastal commented on src/client/utils/form.util.ts
> +    .filter((element) => element[1] !== 'undefined')
RadioButton : pas undefined mais chaine vide

2022-05-25 18:08 UTC, olivocto commented on src/client/components/features/OffreEmploi/Rechercher/RechercherOffreEmploi.tsx
> +                  value={`${tempsDeTravail.valeur}`}
je pense que si car la valuer c'est true ou false

2022-05-30 08:14 UTC, OCTO-CLEM requested changes

2022-05-30 08:14 UTC, OCTO-CLEM commented on src/client/components/features/OffreEmploi/Rechercher/FiltresOffreEmploi.tsx
> +  }, [hasQueryParams, queryParams, localisation ]);
pourquoi pas juste queryParams ? on veut seulement que ca handle quand les params de l'url change nan ?

2022-05-30 08:14 UTC, OCTO-CLEM commented on src/client/utils/form.util.ts
> +    .filter((element) => element[1] !== 'undefined')
pourquoi les 2 filters a la suite comme ca on peut pas les faire en meme temps ?

et pourquoi `element[1]` ?

2022-05-30 08:14 UTC, OCTO-CLEM commented on src/server/offresEmploi/domain/offreEmploi.ts
> +  type contrat = 'CDD' | 'CDI' | 'SAI' | 'MIS'
`Contrat` ? c'est un peu moche avec une minuscule nan ?

2022-05-30 08:14 UTC, OCTO-CLEM commented on src/server/offresEmploi/domain/offreEmploi.ts
> +  grandDomaine: string[]
```suggestion
  grandDomaineList: string[]
```

2022-05-30 08:14 UTC, OCTO-CLEM commented on src/server/offresEmploi/domain/offreEmploi.ts
> +  experienceExigence: string[]
```suggestion
  experienceExigenceList: string[]
```

2022-05-30 08:16 UTC, OCTO-CLEM approved these changes

2022-05-31 08:01 UTC, olivocto commented on src/client/components/features/OffreEmploi/Rechercher/FiltresOffreEmploi.tsx
> +  }, [hasQueryParams, queryParams, localisation ]);
si pas localisatino les filtres ne changent pas mais hasQueryParams est de trop

2022-05-31 13:16 UTC, merged