feat(fiche métier): limit de récup a 100
DNUM-SocialGouv/1j1s-front pull request #515
Opened 2022-11-18 15:28 UTC by OCTO-CLEM

2022-11-18 16:07 UTC, Sefrancois approved these changes

2022-11-18 16:09 UTC, octohuguesdumont requested changes
c'est pas une feat c'est un fix non?

2022-11-21 08:52 UTC, octohuguesdumont approved these changes

2022-11-21 08:54 UTC, OCTO-CLEM commented
bien vu :D

2022-11-21 09:01 UTC, merged