feat: ajout recherche alternance par lieu
DNUM-SocialGouv/1j1s-front pull request #59
Opened 2022-06-10 14:51 UTC by AliElAmrani

2022-06-13 10:09 UTC, olivocto commented on src/server/alternances/infra/repositories/apiLaBonneAlternance.repository.ts
> +    const queryList: Record<string, any> = {
/Volumes/Macintosh HD - Data/Projects/1J1S/1j1s-front/src/server/alternances/infra/repositories/apiLaBonneAlternance.repository.ts
  43:37  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

2022-06-13 11:24 UTC, olivocto commented on src/server/alternances/infra/repositories/apiLaBonneAlternance.repository.ts
> +    const queryList: Record<string, any> = {
peux-tu gérer cette erreur s'il te plaît

2022-06-13 11:41 UTC, paulgallocto commented on src/client/components/features/Alternance/Rechercher/RechercherAlternance.tsx
> +        if(getQueryValue(QueryParams.CODE_INSEE)){
peut-être créer une variable intermédiaire pour stocker le résultat de`getQueryValue(QueryParams.CODE_INSEE` pour éviter de faire 2x le même appel ?

2022-06-13 12:35 UTC, OCTO-CLEM commented on tests/client/components/features/Alternance/Rechercher/RechercherAlternance.test.tsx
> +      // WHEN
il est bien le expect je trouve ici genre y'a un peu 2 parties dans le test. 
1ere partie je recherche une localisation, 2eme partie je recherche mon alternance avec ma localisation.

J'aurais bien vu un 
```
// WHEN - je recherche une localisation
...
// THEN - je veux voir afficher la liste recherchée
...
// WHEN - je recherche une alternance avec ma localisation sélectionnée
...
// THEN - je veux voir voir afficher la liste de alternance filtré par localisation
```

?

2022-06-14 09:53 UTC, olivocto requested changes

2022-06-14 09:53 UTC, olivocto commented on src/client/components/ui/AutoCompletion/AutoCompletionForLocalisation.tsx
> +      if(!isSuggestionListEmpty && ((codeInsee === '' && typeLocalisation === '') || (inputValue && inputValue !== `${!(location) || location[currentIndex].code}`))) {
je ne comprends pas ce que tu fais ici.... comment l'inputValue pourrait être égal a un tableau?

2022-06-14 09:53 UTC, olivocto commented on src/client/components/ui/AutoCompletion/AutoCompletionForLocalisation.tsx
> +      if(!isSuggestionListEmpty && ((codeInsee === '' && typeLocalisation === '') || (inputValue && inputValue !== `${!(location) || location[currentIndex].code}`))) {
il y aune regression par rapport a la recherche sur emplois , la valeur de l'input est vide quand on arrive dans le champ...

2022-06-14 09:53 UTC, olivocto commented on src/client/components/ui/AutoCompletion/AutoCompletionForLocalisation.tsx
> +      const isSuggestionListEmpty = (départementList && départementList.length === 0) && (régionList && régionList.length === 0) && communeList.length === 0;
tu utilises plusieurs fois des choses comme: départementList && départementList.length === 0 (plus bas dans le code aussi)
je tinvite à créer des const du type const hasDépartement = départementList && départementList.length === 0

2022-06-14 10:13 UTC, olivocto requested changes

2022-06-14 10:13 UTC, olivocto commented on src/server/services/utils/urlParams.util.ts
> +export function removeUndefinedValueInQueryParameterList(queryList: Record<string, any>) {
super idée! par contre peux-tu ré-enlever le warning du any dans la console s'il te plaît?
aussi un test pour cette fonction ça coûterait pas très cher

2022-06-14 10:13 UTC, olivocto commented on src/client/components/features/Alternance/Rechercher/RechercherAlternance.tsx
> +        const localisation = await localisationService.récupérerLocalisationAvecCodeInsee(getQueryValue(QueryParams.TYPE_LOCALISATION), getQueryValue(QueryParams.CODE_INSEE));
il se passe quoi ici si t'as pas la localisation et le code insee dans l'url?
spoiler alert: tu as un network error. J'ai des doutes sur le fait que tu ais bien testé l'apllication avant de reproposer ta PR. Je t'invite à relire la DOD

2022-06-14 10:13 UTC, olivocto commented on src/client/components/features/Alternance/Rechercher/RechercherAlternance.tsx
> +    setLocalisationList(résultats ?? { communeList: [], départementList: [], régionList: [] });
je croyais que pour alternance on avait que des communes non?

2022-06-14 10:13 UTC, olivocto commented on src/client/components/features/Alternance/Rechercher/RechercherAlternance.tsx
> +                communeList={localisationList.communeList}
il faut que localisationList soit logique, tu devrais juste avoir à passer communeList

2022-06-17 09:18 UTC, merged