feat(multiple/instantsearch): input select checkbox
DNUM-SocialGouv/1j1s-front pull request #618
Opened 2022-12-15 10:31 UTC by olivocto

2022-12-20 08:50 UTC, octohuguesdumont requested changes

2022-12-20 08:50 UTC, octohuguesdumont commented on src/client/components/layouts/InstantSearch/InstantSearchLayout.module.scss
> +}
manque un retour à la ligne

2022-12-20 08:50 UTC, octohuguesdumont commented on src/client/components/layouts/InstantSearch/ListeDesResultats.module.scss
> +}
Manque un retour à la ligne

2022-12-20 10:30 UTC, Drastal commented on src/client/components/layouts/InstantSearch/InstantSearchLayout.tsx
> +  isResultatFullScreen: boolean
Tu veux plutôt dire si l'affichage est en ligne ou colonne. Utilise le mot clé direction ?

2022-12-20 10:30 UTC, Drastal commented on src/client/components/layouts/InstantSearch/InstantSearchLayout.tsx
> +  const transformItems: CurrentRefinementsProps['transformItems'] = (items) => {
Ça passe en useCallback ? Pour de la perf

2022-12-20 10:30 UTC, Drastal commented on src/client/components/layouts/InstantSearch/InstantSearchLayout.tsx
> +  };
Tu pourrais le sortir de ce composant et lui filer status et results en props ?

2022-12-20 10:30 UTC, Drastal commented on src/client/components/layouts/InstantSearch/ListeDesResultats.module.scss
>      margin: auto;
Est-ce que tu voudrais englober ça dans un composant `Container` qui fait cette logique ?

2022-12-20 10:30 UTC, Drastal commented on src/client/components/layouts/InstantSearch/ListeDesResultats.test.tsx
> +	  it('affiche le skeleton avec le résultat fullscreen', () => {
A adapter

2022-12-20 10:30 UTC, Drastal commented on src/client/components/layouts/InstantSearch/ListeDesResultats.test.tsx
> +	  expect(skeletonList).toBeInTheDocument();
Tu peux checker aussi qu'il n'y a pas de listiem au sein de la list pour vérifier qu'aucune résultat n'est affiché

2022-12-20 10:30 UTC, Drastal commented on src/client/components/layouts/InstantSearch/ListeDesResultats.test.tsx
> +        expect(skeletonList).toHaveClass('skeletonDisplay');
C'est bien de l'avoir testé. Purrait-on avoir un nom qui explicite le fait que ça soit en ligne ?

2022-12-20 10:30 UTC, Drastal commented on src/client/components/layouts/InstantSearch/ListeDesResultats.tsx
> +export const ListeDesResultats = (props: ListeDesResultatsProps) => {
Function. Merci

2022-12-20 10:30 UTC, Drastal commented on src/client/components/layouts/InstantSearch/ListeDesResultats.tsx
> +  isResultatFullScreen: boolean
A adapter

2022-12-20 10:30 UTC, Drastal commented on src/client/components/layouts/InstantSearch/ListeDesResultats.tsx
> +	  <Container className={isResultatFullScreen ? '' : styles.listeDesResultats}>
Va voir dans Bouée

2022-12-20 10:30 UTC, Drastal commented on src/client/components/layouts/InstantSearch/ListeDesResultats.tsx
> +          className={isResultatFullScreen ? '' : styles.skeletonDisplay}
Idem, la bouée

2022-12-20 14:00 UTC, OCTO-CLEM commented on src/client/components/layouts/InstantSearch/InstantSearchLayout.tsx
> +    return items
est ce qu'on ferait pas le capitalized lors de l'important dans le meilisearch ? ca veut dire que la a chaque recherche le bout de code tourne alors qu'on pourrait l'avoir direct dans le meilisearch 1 fois

2022-12-20 14:01 UTC, OCTO-CLEM commented on src/client/components/layouts/InstantSearch/ListeDesResultats.test.tsx
> +describe('ListeDesResultats Component', () => {
stylé ce ptit test :D

2022-12-20 14:03 UTC, OCTO-CLEM commented on src/client/components/ui/Meilisearch/MeiliSearchCustomPagination.tsx
> +    <div className={classNames(className)}>
className={classNames(className)} ? className ?

2022-12-20 14:04 UTC, OCTO-CLEM commented on src/client/components/ui/Meilisearch/MeilisearchCustomRefinementList.tsx
> +          tabIndex={-1}
pour -1 ? ca devrait pas suivre l'index de la liste ?

2022-12-20 14:09 UTC, OCTO-CLEM commented on src/client/components/ui/Meilisearch/tests/MeilisearchCustomRefinementList.test.tsx
> +describe('MeilisearchCustomRefinementList Keyboard', () => {
lourd ca :o

2022-12-20 14:10 UTC, OCTO-CLEM commented on src/client/components/ui/Meilisearch/tests/MeilisearchCustomRefinementList.test.tsx
> +    beforeEach(() => {
regarde ton ide mais t'as des lignes dupliquées genre une dizaine tu pourrais les mettre dans une tite fonction privée ?

2022-12-20 14:33 UTC, olivocto commented on src/client/components/ui/Meilisearch/MeilisearchCustomRefinementList.tsx
> +          tabIndex={-1}
le -1 c'est pour pas que ça prenne le focus, car on ne veut pas le focus sur le li mais sur l'input dans le li

2022-12-20 14:34 UTC, olivocto commented on src/client/components/ui/Meilisearch/MeiliSearchCustomPagination.tsx
> +    <div className={classNames(className)}>
yes, obligé car className vient de CommonProps et peut être un string ou array de string, et si on ne passe pas par le classNames() ça compile pas à cause d'une erreur de type

2022-12-21 12:27 UTC, Drastal approved these changes

2022-12-21 15:20 UTC, olivocto commented on src/client/components/layouts/InstantSearch/InstantSearchLayout.tsx
> +  };
<img width="739" alt="image" src="https://user-images.githubusercontent.com/102825843/208939966-2aaeb976-6a2b-417f-bf9a-8cb4928d1b1d.png">
je peux pas....

2022-12-21 16:01 UTC, merged