feat(actualites): récupération et affichage actualites dans la page m…
DNUM-SocialGouv/1j1s-front pull request #657
Opened 2022-12-27 16:53 UTC by paulgallocto

…esures jeunes

2022-12-29 09:04 UTC, Drastal reviewed
Pas encore fini la review !

2022-12-29 09:04 UTC, Drastal commented on src/client/components/features/EspaceJeune/EspaceJeune.tsx
>              S&apos;orienter et se former
En BSR tu pourrais remplacer ça avec un vrai caractère apostrophe `‘` ? Ça sera plus digeste à la lecture 😋

2022-12-29 10:08 UTC, Drastal requested changes

2022-12-29 10:08 UTC, Drastal commented on src/pages/espace-jeune/index.page.tsx
> +          <div className={styles.cartesActualitesList}>
Je vois que le style `cartesActualitesList` centre le contenu avec une largeur max (entre autres). Il y a-t-il moyen de réutiliser le composant Container à cet effet ?

2022-12-29 10:08 UTC, Drastal commented on src/client/components/ui/Card/AbstractCard/CardComponent.tsx
> +      <Image src={src} alt={''} fill={true} aria-hidden={ariaHidden} style={{ objectFit: 'cover' }}/>
Il y a moyen de passer par une classe ? C'est pour éviter le style inline qui est relevé par Lighthouse

2022-12-29 10:08 UTC, Drastal commented on src/client/components/ui/Card/ArticleCard.tsx
> +  icon?: React.ReactNode
Au lieu de passer un ReactNode, je propose de passer directement le nom de l'icon est c'est ce composant qui, si nom présent, va chercher le composant Icon.

2022-12-29 18:36 UTC, paulgallocto commented on src/client/components/ui/Card/ArticleCard.tsx
> +  icon?: React.ReactNode
Effectivement j'ai pensé à ça au départ, mais j'ai une erreur de typescript, car le nom de l'icon est un parametre typé. Il faudrait donc que je remonte ce type d'icone ici, et j'ai préféré ne pas le faire et rester plus souple et laissant la possibilité d'injecter n'importe quel node

2022-12-30 08:55 UTC, Drastal approved these changes

2022-12-30 10:12 UTC, merged