feat(accompagnement): demande de contact
DNUM-SocialGouv/1j1s-front pull request #659
Opened 2022-12-28 16:40 UTC by Drastal

2022-12-28 17:17 UTC, olivocto commented on src/server/établissement-accompagnement/infra/apiÉtablissementPublic.response.ts
>        telephone: string,
vire moi cette virgule

2022-12-28 17:19 UTC, olivocto commented on src/server/établissement-accompagnement/infra/apiÉtablissementPublic.response.ts
>        telephone: string,
vire moi toutes les virgules

2022-12-28 17:22 UTC, olivocto commented on src/server/établissement-accompagnement/infra/apiÉtablissementPublic.mapper.ts
>      id: feature.properties.id,
aimes tu la destructuration?

2022-12-28 17:25 UTC, olivocto commented on src/server/établissement-accompagnement/domain/ÉtablissementAccompagnement.ts
>    telephone: string;
peux-tu supprimer les points virgules s'il te plait? (emoji implorant)

2022-12-28 17:26 UTC, olivocto commented on src/server/établissement-accompagnement/domain/ÉtablissementAccompagnement.ts
>    telephone: string;
sur tout la page

2022-12-28 17:29 UTC, olivocto commented on src/server/établissement-accompagnement/domain/ÉtablissementAccompagnement.fixture.ts
> +      {
5 petites fixtures ? une petite fonction avec les jours en param et tu connais la suite, c'est comme tu veux

2022-12-28 17:31 UTC, olivocto commented on src/server/établissement-accompagnement/domain/ÉtablissementAccompagnement.fixture.ts
>        adresse: '90 rue Curial, 75019 Paris',
je t'ai connu plus méticuleux sur tes fixtures: à une époque tu m'aurais fait une fixture pour 
{
      adresse: "3-5 rue d'Aligre, 75012 Paris",
      id: '12f15c57-ea33-4ec9-aa34-5e664f742872',
      nom: 'Point information jeunesse - Paris 12e - Maison des ensembles',
      telephone: '01 53 46 75 10',
      type: TypeÉtablissement.INFO_JEUNE,
    }

2022-12-28 17:32 UTC, olivocto commented on src/server/services/serverConfiguration.service.ts
> +  readonly MAILER_SERVICE_ACTIVE: string
point virgule or not point virgule il faut choisir?

2022-12-28 17:47 UTC, olivocto commented on src/server/demande-de-contact/useCases/envoyerDemandeDeContactCEJ.usecase.ts
>  type EnvoyerDemandeDeContactCEJ = Partial<{
a toi te voir moi j'aime bien les interfaces

2022-12-28 17:52 UTC, olivocto commented on src/server/demande-de-contact/infra/tipimailDemandeDeContact.repository.ts
> +        if (e.response?.status === 401) {
utile ce if si on retourne déjà en dessous?

2022-12-28 17:55 UTC, olivocto commented on src/server/demande-de-contact/infra/tipimailDemandeDeContact.repository.test.ts
> +      it('N‘envoie pas le mail', async () => {
petit n pas la peine de voir le n en grand

2022-12-28 17:57 UTC, olivocto commented on src/server/demande-de-contact/infra/tipimailDemandeDeContact.repository.test.ts
> +        it('renvoie une erreur demande incorrecte', async () => {
erreur de description

2022-12-29 08:32 UTC, olivocto commented on src/server/demande-de-contact/domain/demandeDeContact.ts
> +export function parseAge(a: number): Age {
peux-tu appeler ce paramètre age please, on n'est plus à 2 lettres près

2022-12-29 08:47 UTC, olivocto commented on src/client/services/lesEntreprisesSEngagent/lesEntreprisesSEngagent.service.test.ts
>      it('revoie un Success', async () => {
typo renvoie

2022-12-29 08:47 UTC, olivocto commented on src/client/services/lesEntreprisesSEngagent/lesEntreprisesSEngagent.service.test.ts
>      it('revoie une Failure', async () => {
idem

2022-12-29 08:48 UTC, olivocto commented on src/client/services/httpClient.service.ts
> +      if(e.response?.status === 404) {
contenu indisponible pour une 404 ? sommes-nous sur?

2022-12-29 08:49 UTC, olivocto commented on src/client/services/httpClient.service.ts
> +      if(e.response?.status === 404) {
ne serait-il pas temps d'avoir des ERREUR METIERS moins regroupé et plus précis?

2022-12-29 08:50 UTC, olivocto commented on src/client/components/ui/ErrorMessage/NoResultErrorMessage.tsx
> +      solutionText="Vérifiez l‘orthographe, essayez d‘autres mots-clés ou élargissez votre zone géographique de recherche." />
je pense que ce BSR peut être fait partout, je ne sais pas si tu la fais dans cette pr

2022-12-29 08:51 UTC, olivocto commented on src/client/components/layouts/RechercherSolution/Résultat/RésultatRechercherSolution.tsx
> +        <TextIcon icon="angle-right" className={styles.callToAction}>En savoir plus</TextIcon>
ça c'est beau

2022-12-29 08:55 UTC, olivocto commented on src/client/components/features/Accompagnement/DemandeDeContact/Formulaire/FormulaireDemandeDeContactAccompagnement.test.tsx
> +});
il manque tous les tests de navigation claviers, sommes-nous sur que le formulaire est accessible?

2022-12-29 08:58 UTC, olivocto commented on src/client/components/features/Accompagnement/DemandeDeContact/ModalDemandeDeContactAccompagnement.tsx
> +          <div className={styles.success}>
ce bout de code, c'est pas la 4ème fois qu'il apparaît dans la codebase? Il serait temps de lui offrir un peu de réusabilité...

2022-12-29 09:00 UTC, olivocto commented on src/client/components/layouts/RechercherSolution/RechercherSolutionLayout.tsx
>    bannière: React.ReactNode
bah tu me dis on type tout en ReactElement et tu mets des reactNode partout

2022-12-29 09:01 UTC, OCTO-CLEM commented on src/client/components/features/Accompagnement/DemandeDeContact/Formulaire/FormulaireDemandeDeContactAccompagnement.test.tsx
> +      await userEvent.type(screen.getByLabelText('Adresse e-mail (facultatif)'), demandeDeContactAccompagnement.email);
ptite fonction privée de setup ?

2022-12-29 09:07 UTC, olivocto commented on src/client/components/features/JobÉtudiant/Rechercher/RechercherJobÉtudiant.tsx
> +          étiquettesRecherche={offreEmploiQuery.libelleLocalisation ?
perso, je sortirais ça, là c'est pas ouf

2022-12-29 09:08 UTC, olivocto commented on src/client/components/features/Engagement/Rechercher/RechercherMission.tsx
> +    <ListeRésultatsRechercherSolution aria-label={isServiceCivique ? 'Offre pour le service civique' : 'Offre pour le bénévolat'}>
la condition ne pourraot switcher qu'entre service-cique ou bénévolat comme mot

2022-12-29 09:12 UTC, olivocto commented on src/client/components/features/Alternance/Rechercher/RechercherAlternance.tsx
> +          étiquettesRecherche={offreQuery.libelleLocalisation ?
pareil que commentaire en dessous

2022-12-29 09:13 UTC, olivocto commented on src/client/components/features/Alternance/Rechercher/RechercherAlternance.tsx
> +import { RésultatRechercherSolution } from '../../../layouts/RechercherSolution/Résultat/RésultatRechercherSolution';
relative path manqué

2022-12-29 09:19 UTC, olivocto commented on src/client/components/features/Accompagnement/Rechercher/RechercherAccompagnement.tsx
> +          étiquettesRecherche={accompagnementQuery.libelleCommune ?
je te laisse voir si tu veux faire un peu de propre

2022-12-29 09:21 UTC, olivocto reviewed
quelques commentaires

2022-12-29 10:14 UTC, Drastal commented on src/server/établissement-accompagnement/infra/apiÉtablissementPublic.mapper.ts
>      id: feature.properties.id,
La réponse est non 😁

2022-12-29 10:17 UTC, OCTO-CLEM commented
Remarque sur l'archi back je trouve ca hyper moche d'avoir une interface `DemandeDeContact` et `DemandeDeContactAccompagnement` c'est très clairement un bad smell pour moi, genre la on crée une interface "juste" parce que derrière on a pas la meme implem de repo avant c'était des envoies sur strapi et maintenant on envoie par mail, on devrait pas savoir ca coté domain

Moi j'aurais fait une interface 
```
export interface DemandeDeContactRepository {
  envoyer(demandeDeContact: DemandeDeContact): Promise<Either<void>>;
}
```

Pourquoi ? parce qu'on est parti du principe que notre métier c'était d'**envoyer demande de contact**, du coup la on est entrain de commencer a spécifier dans notre domain qu'est ce qu'on en entrain de faire dans nos répo en mode j'envoie sur une bdd, j'envoie par email.

Du coup je ferais une interface "envoyer" qui a 4 implems de répo, c'est pas très coûteux et ca sera vraiment plus propre apres dans notre métier

2022-12-29 10:23 UTC, Drastal commented on src/client/components/ui/ErrorMessage/NoResultErrorMessage.tsx
> +      solutionText="Vérifiez l‘orthographe, essayez d‘autres mots-clés ou élargissez votre zone géographique de recherche." />
Je vais le faire dans une PR à part, ça fait trop de bruit

2022-12-29 10:25 UTC, OCTO-CLEM requested changes

2022-12-29 10:25 UTC, OCTO-CLEM commented on src/client/components/features/Accompagnement/Rechercher/RésultatRechercherAccompagnementMobile.tsx
> +  const logoÉtablissement = useMemo(() => {
y'a la meme logique dans les 2 ? j'imagine que si l'un change l'autre aussi nan ?

2022-12-29 10:25 UTC, OCTO-CLEM commented on src/client/services/httpClient.service.ts
> +      if(e.response?.status === 404) {
404 = ressource non trouvée

moi perso je trouve se limiter a 3, 4 erreurs c'est bien sinon ca devient vite le bordel avec des erreurs un peu partout utiliser a toutes les sauces, mais c'est mon avis

2022-12-29 10:25 UTC, OCTO-CLEM commented on src/client/services/lesEntreprisesSEngagent/lesEntreprisesSEngagent.service.test.ts
>      it('revoie un Success', async () => {
d'ailleurs c'est pas renvoit ?

2022-12-29 10:25 UTC, OCTO-CLEM commented on src/client/services/établissementAccompagnement/établissementAccompagnement.service.ts
> +    return this.httpClientService.get<ÉtablissementAccompagnement[]>(`etablissements-accompagnement?${stringify(JSON.parse(JSON.stringify(queryParams)))}`);
wttttffff `stringify` de `JSON.parse` de `JSON.stringify` ?

2022-12-29 10:25 UTC, OCTO-CLEM commented on src/server/demande-de-contact/infra/tipimailDemandeDeContact.repository.ts
> +        // eslint-disable-next-line no-console
console.debug ?

2022-12-29 10:35 UTC, Drastal commented on src/server/établissement-accompagnement/domain/ÉtablissementAccompagnement.fixture.ts
> +      {
Ça marche pas trop, les horaires sont différents en fonction des jours. Je laisse tel quel

2022-12-29 10:37 UTC, Drastal commented on src/server/établissement-accompagnement/domain/ÉtablissementAccompagnement.fixture.ts
>        adresse: '90 rue Curial, 75019 Paris',
Pas compris ta remarque 😅

2022-12-29 10:44 UTC, Naorid commented
Note : Il y a des retours UI de Joy sur le formulaire à prendre en compte : https://jira-mcas.atlassian.net/browse/UNJ1S-873?focusedCommentId=47805

2022-12-29 10:47 UTC, Drastal commented on src/client/services/httpClient.service.ts
> +      if(e.response?.status === 404) {
Quels sont nos autres besoins ?
Ici il faut lisser les gestions des codes HTTP sur tout notre front. Ce qu'on pourrait faire c'est associer un message d'erreur envoyé par le back et l'envoyer au front pour que ç asoit notre BFF qui détienne cette logique métier.

2022-12-29 10:52 UTC, Drastal commented on src/client/components/features/Accompagnement/DemandeDeContact/ModalDemandeDeContactAccompagnement.tsx
> +          <div className={styles.success}>
La classe ? Elle ne fait pas la même chose selon les pages. Je ne vois pas grand chose de réutilisable 🤔 
Il faudrait lisser les comportements sur le site

2022-12-29 11:01 UTC, Drastal commented on src/client/components/layouts/RechercherSolution/RechercherSolutionLayout.tsx
>    bannière: React.ReactNode
C'est plus précis, si on sait qu'on doit avoir un composant React en paramètre. Je change

2022-12-29 13:01 UTC, Drastal commented on src/client/components/features/Engagement/Rechercher/RechercherMission.tsx
> +    <ListeRésultatsRechercherSolution aria-label={isServiceCivique ? 'Offre pour le service civique' : 'Offre pour le bénévolat'}>
La phrase complète est plus lisible comme ça. On ne gagne vraiment pas grand chose. Je vais laisser comme ça.

2022-12-29 13:06 UTC, Drastal commented on src/server/demande-de-contact/infra/tipimailDemandeDeContact.repository.ts
> +        // eslint-disable-next-line no-console
J'ai passé en log, c'est mieux que debug. L'idée est d'avoir le mail dans la console du serveur si le mailer est désactivé. Pour vérifier que ça fonctionne tout de même bien.

2022-12-29 13:18 UTC, Drastal commented on src/client/components/features/Accompagnement/Rechercher/RésultatRechercherAccompagnementMobile.tsx
> +  const logoÉtablissement = useMemo(() => {
Aller j'en fait un hook 😃 
Par contre je le laisse dans ce dossier, il n'est pas du tout utilisé en dehors de ce context

2022-12-29 13:44 UTC, Naorid approved these changes

2022-12-29 13:57 UTC, Drastal commented on src/client/components/features/Accompagnement/DemandeDeContact/ModalDemandeDeContactAccompagnement.tsx
> +          <div className={styles.success}>
Composant de layout à faire sûrement. A prendre séparément

2022-12-29 16:01 UTC, Drastal commented on src/client/components/features/Accompagnement/Rechercher/RésultatRechercherAccompagnement.tsx
>    return `${split[0]}h${split[1] !== '00' ? split[1] : ''}`;
Je viens de créer des petits composants pour la gestion des horaires :)

2022-12-29 16:01 UTC, Drastal commented on src/client/components/features/Accompagnement/Rechercher/RésultatRechercherAccompagnement.tsx
>    return `${split[0]}h${split[1] !== '00' ? split[1] : ''}`;
Et ils sont tesés maintenant, via RTL

2022-12-29 16:02 UTC, Drastal commented on src/client/components/features/Accompagnement/Rechercher/RésultatRechercherAccompagnement.tsx
>    if (heure.length > 1) {
Maintenant nouveaux composants pour tester ça finement !

2022-12-29 16:30 UTC, Drastal commented on src/client/components/features/Accompagnement/DemandeDeContact/ModalDemandeDeContactAccompagnement.tsx
> +              onSubmit={onSubmit}
Pas exactement, ça serait () => setIsSuccess(true)
Je fais ça

2022-12-29 16:33 UTC, Drastal commented on src/client/components/features/Accompagnement/DemandeDeContact/Formulaire/FormulaireDemandeDeContactAccompagnement.tsx
> +  }
Cas absolument pas spécifié 😇

2022-12-29 16:33 UTC, Drastal commented on src/client/components/features/Accompagnement/DemandeDeContact/Formulaire/FormulaireDemandeDeContactAccompagnement.tsx
> +  const { contactÉtablissementAccompagnement, onSubmit } = props;
J'ai renommé en `onSuccess`

2022-12-29 16:34 UTC, Drastal commented on src/server/demande-de-contact/domain/demandeDeContactAccompagnement.repository.ts
> +  send(demandeDeContactAccompagnement: DemandeDeContactAccompagnement): Promise<Either<void>>
Les `;` sont totalement optionnelles pour les interfaces. On se dit qu'on en met aucune ?

2022-12-30 17:09 UTC, OCTO-CLEM approved these changes

2022-12-30 18:44 UTC, merged