feat(checkbox): ajout gestion focus sur composant checkbox
DNUM-SocialGouv/1j1s-front pull request #749
Opened 2023-01-17 15:13 UTC by paulgallocto

2023-01-17 15:51 UTC, Drastal requested changes

2023-01-17 15:51 UTC, Drastal commented on src/client/components/ui/Checkbox/Checkbox.tsx
> +			<label className={styles.label} htmlFor={checkboxId.current} tabIndex={0} onKeyDown={handleKeyboardEvent}>{label}</label>
J'arrive toujours à avoir le focus sur l'input 😬 
Je pense que le style devrait target `input:focus + label:before`, et ne pas avoir tabIndex ici. On devrait retomber sur nos pattes.
Et dans ce cas là il ne devrait même plus y avoir besoin du onKeyDown puisque c'est géré nativement par l'input.

2023-01-17 16:52 UTC, paulgallocto commented on src/client/components/ui/Checkbox/Checkbox.tsx
> +			<label className={styles.label} htmlFor={checkboxId.current} tabIndex={0} onKeyDown={handleKeyboardEvent}>{label}</label>
Non ça ne fonctionnera pas car l'input native est masquée avec une opacité à 0 :/

2023-01-18 08:11 UTC, Drastal commented on src/client/components/ui/Checkbox/Checkbox.tsx
> +			<label className={styles.label} htmlFor={checkboxId.current} tabIndex={0} onKeyDown={handleKeyboardEvent}>{label}</label>
Applique ceci comme règle, à l'intérieur du sélecteur `input[type=checkbox]`, et la magie opérera ✨ 
```
    &:focus + label:before {
      outline: 2px solid $color-primary;
      outline-offset: 2px;
    }
```

2023-01-18 10:01 UTC, Drastal approved these changes

2023-01-18 10:01 UTC, merged