fix(config): mis a jour next config
DNUM-SocialGouv/1j1s-front pull request #818
Opened 2023-01-30 13:00 UTC by olivocto

2023-01-30 13:38 UTC, Drastal requested changes

2023-01-30 13:38 UTC, Drastal commented on next.config.js
> +if (process.env.NODE_ENV === 'production' || process.env.NODE_ENV === 'integration') {
NODE_ENV ne peut avoir que 3 valeurs :
* `test`
* `development`
* `production`
Il faut arrêter d'utiliser les autres, nous n'utilisons plus `integration`

2023-01-30 13:45 UTC, LiquidITGuy commented on next.config.js
> +	moduleExports.sentry = sentryModuleExports;
est-il possible de résoudre le problème sans la mutation ?

2023-01-30 13:45 UTC, Drastal commented on next.config.js
> +if (process.env.NODE_ENV === 'production' || process.env.NODE_ENV === 'integration') {
Il y a tout de même un changement de comportement ici, c'est bien voulu ? Là la config Sentry ne sera active que lorsqu'on utilise un npm run build, en local compris. Il y a une éventuelle adhérence avec la fonction `shouldUploadSourceMap`

2023-02-01 13:25 UTC, Drastal approved these changes

2023-02-01 14:30 UTC, merged