feat(alternance): 1269 retour recette
DNUM-SocialGouv/1j1s-front pull request #930
Opened 2023-02-15 16:34 UTC by Naorid

2023-02-17 10:23 UTC, Mintoo200 reviewed
<img width="470" alt="image" src="https://user-images.githubusercontent.com/25901730/219611534-28dbed37-31a3-4e42-ac31-dc06c90eb341.png">

2023-02-17 10:23 UTC, Mintoo200 commented on cypress/e2e/apprentissage.cy.ts
> +			cy.contains('Conduite de travaux, direction de chantier').should('be.visible');
C'est étrange dans un test e2e de taper Barman dans la barre de recherche et d'arriver sur Conduite de travaux

2023-02-17 10:23 UTC, Mintoo200 commented on cypress/e2e/apprentissage.cy.ts
> +			cy.contains('Robotique, systèmes automatisés').should('not.be.visible');
Il faudrait expliciter que ces valeurs là sont bien dans la fixture, en l'état on a besoin de savoir qu'ils y sont pour comprendre le test, sans compter que si je supprime "Robotique, systèmes automatisés" de la fixture, je peux rendre ce test toujours vert sans savoir (puisque je n'y ait pas touché directement)

2023-02-17 10:23 UTC, Mintoo200 commented on src/client/components/features/Alternance/FormulaireRecherche/FormulaireRechercheAlternance.test.tsx
> +			await waitFor(() => user.click(screen.getByRole('option', { name: 'Conduite de travaux, direction de chantier' })));
Il vaut mieux utiliser `await user.<truc>(...)` que `waitFor` qui test jusqu'au timeout et donc masque le message d'erreur et ne fail qu'après avoir timeout (5 secondes par défaut)

2023-02-17 10:23 UTC, Mintoo200 commented on src/client/components/features/Alternance/FormulaireRecherche/FormulaireRechercheAlternance.test.tsx
> +			expect(routerPush).toHaveBeenCalledWith({ query: 'libelle=Conduite+de+travaux%2C+direction+de+chantier&codeRomes=F1201%2CF1202%2CI1101' }, undefined, { shallow: true });
Si vous avez fait ces modifs parce que vous avez changé la fixture et que ça a pété vos tests, ça serait une bonne occasion d'expliciter le contenu de la fixture au début du test (cf. commentaire sur le test cypress).

2023-02-17 10:23 UTC, Mintoo200 commented on src/client/components/ui/Form/InputAutocomplétion/InputAutocomplétionMétier/InputAutocomplétionMétier.test.tsx
> +			expect(screen.getByRole('option', { name: 'Aéronautique' })).toBeInTheDocument();
Préférer `.toBeVisible()` qui test non-seulement qu'il est dans le document mais aussi qu'il n'a pas d'attribut `hidden` ou de style inline qui le masque

2023-02-17 10:23 UTC, Mintoo200 commented on src/client/components/ui/Form/InputAutocomplétion/InputAutocomplétionMétier/InputAutocomplétionMétier.test.tsx
> +				await waitFor(() => user.click(screen.getByRole('option', { name: 'Conduite de travaux, direction de chantier' })));
cf. commentaire `waitfor`

2023-02-17 10:23 UTC, Mintoo200 commented on src/client/components/ui/Form/InputAutocomplétion/InputAutocomplétionMétier/InputAutocomplétionMétier.test.tsx
> +				await screen.findByRole('option', { name: 'Conduite de travaux, direction de chantier' });
Plutôt que d'`await findByRole` qui rend les tests très lents quand ils failent (cf. commentaire `waitFor`), il serait intéressant d'injecter le timeout dans le composant à l'image de l'`InputLocalisation.tsx`

2023-02-17 10:23 UTC, Mintoo200 commented on src/client/components/ui/Form/InputAutocomplétion/InputAutocomplétionMétier/InputAutocomplétionMétier.test.tsx
> +				await waitFor(() => expect(inputAutocomplétionMétier).toHaveValue('Ingéniérie en BTP (Bureau d études, conception technique, BIM, …)'));
Il est nécessaire ce `waitFor` ? (étant donné qu'on `await` l'appel à `userEvent` au dessus)

2023-02-17 10:41 UTC, Mintoo200 requested changes
Désolé pour le bruit, je la passe en Changes Requested pour plus qu'elle apparaisse en Review Required

2023-02-17 11:21 UTC, juliebrunetto83 commented on cypress/e2e/apprentissage.cy.ts
> +			cy.get('ul[role="listbox"] > li').should('have.length', 11);
Il y a bien 11 éléments mais il y en a 10 au maximum de visible (sinon il faut scroller)

2023-02-20 12:57 UTC, Mintoo200 requested changes

2023-02-20 12:57 UTC, Mintoo200 commented on src/client/components/ui/Form/InputAutocomplétion/InputAutocomplétionMétier/InputAutocomplétionMétier.tsx
> +			{isRechercheIndisponible && <p className={styles.instructionMessageError} id={errorId.current}>{ERROR_RETRIEVE_METIER}</p>}
<img width="432" alt="image" src="https://user-images.githubusercontent.com/25901730/220112813-4fe499ae-a350-44f2-96a1-ff2744277388.png">
C'est le comportement attendu ? Ça parait étrange de dire à l'utilisateur qu'il n'a pas sélectionné un métier valide s'il n'a même pas pu voir la liste. Je pense qu'il serait plus simple d'utiliser le message d'erreur de l'input lui-même plutôt que de redéfinir un message manuellement, le composant `<InputText />` par exemple prend en props une fonction de validation custom, ça peut être ˆêtre une piste

2023-02-20 12:57 UTC, Mintoo200 commented on src/server/alternances/infra/repositories/apiLaBonneAlternance.mapper.ts
> +			tags: [alternance.place?.city, ...alternance.job.contractType, alternance.diplomaLevel].filter((tag) => !!tag) as string[],
Le typage n'est pas compatible ici puisque `alternance.place?.city` peut être null ou undefined, ça peut poser problème plus loin vu que ça sera typé en `string[]` et qu'on a envie de faire confiance au typage

2023-02-20 13:01 UTC, juliebrunetto83 commented on src/server/alternances/infra/repositories/apiLaBonneAlternance.mapper.ts
> +			tags: [alternance.place?.city, ...alternance.job.contractType, alternance.diplomaLevel].filter((tag) => !!tag) as string[],
C'est pour ça que j'avais mis un filter qui enlève les champ undefined , j'avais des problème de undefined qui se transformait en null quand la donnée arrive dans le front

2023-02-20 16:49 UTC, Mintoo200 approved these changes

2023-02-20 17:09 UTC, merged