feat(formation): Recherche formation par métier
DNUM-SocialGouv/1j1s-front pull request #963
Opened 2023-02-22 12:50 UTC by Naorid

2023-02-23 10:50 UTC, olivocto requested changes

2023-02-23 10:50 UTC, olivocto commented on src/client/components/features/Formation/Résultat/RésultatRechercherFormation.tsx
> +export interface RésultatRechercherAlternanceProps {
revoir le nommage

2023-02-23 10:50 UTC, olivocto commented on src/client/components/features/Formation/Rechercher/RechercherFormation.tsx
> +	);
un fichier de test pour vérifier l'appel au service et l'affichage de la liste de résultats serait pas mal

2023-02-23 11:14 UTC, Naorid commented on src/server/formations/infra/repositories/apiLaBonneAlternanceFormation.ts
> +		diplomaLevel?: string
👍 
Je l'ai mis coté domain mais je laisse string dans le type api parce que c'est spécifié nulle part que c'est les seuls valeurs possible

2023-02-23 11:15 UTC, Naorid commented on src/server/formations/domain/formation.mapper.ts
> +}
Je sais pas pour toi mais mon IDE aime pas quand je mets [3], il préfère le string complet 🤔

2023-02-23 19:37 UTC, olivocto commented on src/client/components/features/Formation/FormulaireRecherche/FormulaireRechercheFormation.module.scss
> +.rechercheOffreForm {
rechercheFormationForm?

2023-02-23 19:40 UTC, olivocto commented on src/client/components/features/Formation/Rechercher/RechercherFormation.test.tsx
> +			const resultList = await within(await screen.findByRole('list', { name: 'Formations en alternance' })).findAllByTestId('RésultatRechercherSolution');
je veux bien un const intermédiaire pour pas avoir le findByRole dan s le within...

2023-02-23 19:46 UTC, olivocto commented on src/server/formations/domain/formation.mapper.ts
> +		case '3 (CAP...)':
tu veux pas créer un enum aussi pour les case?
un enum coté DTO et un enum coté object métier

2023-02-24 07:48 UTC, juliebrunetto83 commented on src/client/components/features/Formation/Rechercher/RechercherFormation.test.tsx
> +			const resultList = await within(await screen.findByRole('list', { name: 'Formations en alternance' })).findAllByTestId('RésultatRechercherSolution');
Il y a pas un autre moyen qu'avec un findAllByTestId ?

2023-02-24 08:42 UTC, Naorid commented on src/client/components/features/Alternance/Rechercher/RechercherAlternance.tsx
> +	const getLogo = (alternance: Alternance) =>  {
Je peux pas a cet endroit vu qu'on est pas dans le composant de base. Cette fonction est appellé dans le map pour traiter chaque offre d'alternance :/

2023-02-24 08:47 UTC, Naorid commented on src/server/formations/domain/formation.mapper.ts
> +		case '3 (CAP...)':
Je t'en avais parlé, étant donné que rien indique que l'api respecte ce format, je préfère mettre string (c'est pour ça qu'il y a un cas "Autre" d'ailleurs)

2023-02-24 16:01 UTC, olivocto approved these changes

2023-02-24 16:04 UTC, merged