refactor(engagement): déplacement du publisher
DNUM-SocialGouv/1j1s-front pull request #972
Opened 2023-02-23 22:27 UTC by Drastal

Déplacement de constantes de l'API Engagement (publisher ID) du controller vers le repository

2023-02-24 09:27 UTC, Mintoo200 requested changes

2023-02-24 09:27 UTC, Mintoo200 commented on src/server/engagement/infra/repositories/apiEngagement.repository.test.ts
> +			});
Étant donné qu'on ne spécifie pas dans le test les filtres qu'on veut, je peux modifier la fixture et faire peter le test sans avoir touché ni au test ni à la feature. Dans le cas de ce test, je serais OK pour soit ne matcher que le "/mission/search" et faire un test qui check les query params, soit garder en 1 test mais ne matcher que des params explicité à l'instanciation de la fixture

2023-02-24 09:27 UTC, Mintoo200 commented on src/server/engagement/infra/repositories/apiEngagement.repository.test.ts
> +				expect(errorType).toEqual(ErreurMétier.SERVICE_INDISPONIBLE);
même commentaire que sur le test précédent

2023-02-24 09:27 UTC, Mintoo200 commented on src/server/engagement/infra/repositories/apiEngagement.repository.test.ts
> +				expect(httpClientService.get).toHaveBeenCalledWith('mission/search?domain=sante&from=0&publisher=5f99dbe75eb1ad767733b206&size=15&openToMinors=yes&distance=10km&lat=2.3522&lon=48.8566');
cet expect ne correspond pas à ce qui est testé ici ?

2023-02-24 09:27 UTC, Mintoo200 commented on src/server/engagement/infra/repositories/apiEngagement.repository.test.ts
> +				expect(httpClientService.get).toHaveBeenCalledWith('mission/search?domain=sante&from=0&publisher=5f5931496c7ea514150a818f&size=15&openToMinors=yes&distance=10km&lat=2.3522&lon=48.8566');
Fonctionnellement, l'ordre des params n'impacte rien, c'est donc étrange d'avoir un changement dans ce test alors que le fonctionnement n'a pas changé

2023-02-24 09:27 UTC, Mintoo200 commented on src/server/engagement/infra/repositories/apiEngagement.repository.ts
> +const SERVICE_CIVIQUE_PUBLISHER_ID = '5f99dbe75eb1ad767733b206';
Est-ce que ça ne vaudrait pas le coup de mettre ça dans des variables d'env ?

2023-02-24 09:27 UTC, Mintoo200 commented on src/server/services/utils/urlParams.util.ts
> +}
Tu peux inverser le filtre et l'instanciation des SearchParams pour ne pas append à chaque fois : 
```suggestion
export function transformObjectToQueryString<T extends object>(source: T): string {
    const filteredParams = Object.entries(source).filter(([key, value]) => (
        ALLOWED_QUERY_PARAMS_TYPE_LIST.includes(typeof value)
    ))
    const urlSearchParams = new URLSearchParams(filteredParams);

    return urlSearchParams.toString();
}
```
Du coup tu n'utilise plus la `key` donc tu peux te servir de `Object.values()` plutôt qu'`Object.entries()` : 
```suggestion
export function transformObjectToQueryString<T extends object>(source: T): string {
    const filteredParams = Object.values(source).filter((value) => (
        ALLOWED_QUERY_PARAMS_TYPE_LIST.includes(typeof value)
    ))
    const urlSearchParams = new URLSearchParams(filteredParams);

    return urlSearchParams.toString();
}
```

2023-02-24 10:38 UTC, Drastal commented on src/server/engagement/infra/repositories/apiEngagement.repository.test.ts
> +				expect(httpClientService.get).toHaveBeenCalledWith('mission/search?domain=sante&from=0&publisher=5f5931496c7ea514150a818f&size=15&openToMinors=yes&distance=10km&lat=2.3522&lon=48.8566');
Je remplace par plein de `stringMatching`

2023-02-24 15:58 UTC, Drastal commented on src/server/engagement/infra/repositories/apiEngagement.repository.ts
> +const SERVICE_CIVIQUE_PUBLISHER_ID = '5f99dbe75eb1ad767733b206';
Ce n'est pas configurable par environnement mais ça reste de la conf' de l'API. Je préfère temporiser cette suggestion pour la faire quand ça sera nécessaire 😁

2023-02-24 16:07 UTC, Drastal commented on src/pages/api/services-civique/index.controller.ts
> +	}
Ce ne sont pas les mêmes objets. J'ai initié un nouveau typage. Tu me dis ce que tu en penses ?

2023-02-28 17:16 UTC, Mintoo200 approved these changes

2023-02-28 17:17 UTC, merged